### PR TITLE
fix(bin_decoder): fix build warnings when decompressing LZ4 compressed images

### LINKED ISSUE #7787: lv_bin_decoder produces build warnings when decompressing LZ4 compressed images
### LVGL version

v9.2.2

### Platform

- ESP32-S3 using ESP-IDF plugging within Visual Studio Code.
- LV_USE_LZ4 is enabled
- Using images compressed using LZ4

### What happened?

In `lv_bin_decoder.c` within the `decompress_image()` function, one of the print format specifiers is incorrect. `len`, which is an `int` uses the `LV_PRId32` format specifier:

https://github.com/lvgl/lvgl/blob/589e8ac994dbdbe1729fce0a865106e94ee5b8c3/src/libs/bin_decoder/lv_bin_decoder.c#L1155

As a result the following warning (treated as an error) is produced:

```
managed_components/lvgl__lvgl/src/libs/bin_decoder/lv_bin_decoder.c:1138:25: error: format '%ld' expects argument of type 'long int', but argument 7 has type 'int' [-Werror=format=]
 1138 |             LV_LOG_WARN("Decompress failed: %" LV_PRId32 ", got: %" LV_PRId32, out_len, len);
      |                         ^~~~~~~~~~~~~~~~~~~~~~                                          ~~~
      |                                                                                         |
      |                                                                                         int
```

### Proposed fix options

A simple fix would be to change the line to:

```
 LV_LOG_WARN("Decompress failed: %" LV_PRId32 ", got: %d", out_len, len);
```

However, I believe that there are other issues in the `decompress_image()` function that it might be good to address at the same time. I believe for example that `out_len` is also using the wrong format specifier, but this is not flagged because the variable is cast to void with the `LV_UNUSED()` macro. In addition to this, there is the opportunity to reduce some repeated code.

The following relatively small change could we applied as an alternative to the above:
https://github.com/lvgl/lvgl/commit/7fd1351e40fe2beee6332b8ece3b5937092aeed4

Or a more substantial change, with additional refactoring could be applied. I have prepared a branch, which can be found here:
https://github.com/chrismapp/lvgl/tree/bugfix-lv-bin-decoder-incorrect-print-format-specifier

I'd be happy to raise a pull request, but wanted to get some feedback on what would be the most appropriate way to fix the issue before I do.

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by chrismapp**
Fixes #7787 

- Change print format specifiers and use intermediate variable to set decompression length
- Refactor to remove repeated code and improve readability

### CODE REVIEW

File: src/libs/bin_decoder/lv_bin_decoder.c [hunk 1]
```diff
@@ -1098,6 +1098,26 @@ static lv_fs_res_t fs_read_file_at(lv_fs_file_t * f, uint32_t pos, void * buff,
 
 static lv_result_t decompress_image(lv_image_decoder_dsc_t * dsc, const lv_image_compressed_t * compressed)
 {
+    // At least one compression method must be enabled
```
Comment (FASTSHIFT) [inline src/libs/bin_decoder/lv_bin_decoder.c]: Use C-style comments
```c
/* At least one compression method must be enabled */
```

File: src/libs/bin_decoder/lv_bin_decoder.c [hunk 2]
```diff
@@ -1098,6 +1098,26 @@ static lv_fs_res_t fs_read_file_at(lv_fs_file_t * f, uint32_t pos, void * buff,
...
+#endif
+    }
+    else if(compressed->method == LV_IMAGE_COMPRESS_LZ4) {
+#if !LV_USE_LZ4
+        LV_LOG_WARN("LZ4 decompression is not enabled");
+        return LV_RESULT_INVALID;
+#endif
+    }
+    else {
+        LV_LOG_WARN("Unknown compression method: %d", compressed->method);
```
Comment (liamHowatt) [inline src/libs/bin_decoder/lv_bin_decoder.c]:
```suggestion
        LV_LOG_WARN("Unknown compression method: %" LV_PRIu32, compressed->method);
```

**Review by liamHowatt — COMMENTED** [review]
Thanks for opening a PR! It makes sense to me!

**Review by liamHowatt — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]

**Comment by FASTSHIFT** [comment]
cc @XuNeo

**Review by uLipe — APPROVED** [review]
