### PR TITLE
fix(draw) overlap outline with background to prevent aliasing artifacts

### LINKED ISSUE #2064: Weirdness with antialiasing and border
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

This isn't a major bug, but it's been bothering me for a while now. The antialiasing on objects with a border seems to choose the wrong color to blend with sometimes, resulting in an ugly line between the object edge and the start of the border.

This might be how it's intended to behave, but I figured it was worth clarifying.

### To Reproduce

Visit https://lvgl.github.io/lv_examples/lv_demo_widgets/index.html (or run `lv_demo_widgets`), enable Dark mode, and toggle the switch inside "Basics".

### Expected behavior

The blend should be smoother (more like the horizontal portions of the switch).

### Screenshots or video

screenshot

### PR DESCRIPTION
**Pull request by embeddedt**
### Description of the feature or fix

Fixes #2064.

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

File: src/lv_draw/lv_draw_rect.c [hunk 1]
```diff
@@ -1160,18 +1160,21 @@ static void draw_outline(const lv_area_t * coords, const lv_area_t * clip, const
     /*Get the inner radius*/
     lv_area_t area_inner;
     lv_area_copy(&area_inner, coords);
-    area_inner.x1 -= dsc->outline_pad;
-    area_inner.y1 -= dsc->outline_pad;
-    area_inner.x2 += dsc->outline_pad;
-    area_inner.y2 += dsc->outline_pad;
+
+    lv_coord_t pad = dsc->outline_pad - 1;
```
Comment (kisvegabor) [inline src/lv_draw/lv_draw_rect.c]: I think it should be added only if pad == 0

**Review by kisvegabor — COMMENTED** [review]
Thanks!

BTW, do you have any idea why the build fails? It complains about `cast` but it seems correct.

**Comment by kisvegabor** [comment]
Started to fail on this commit which seems completely unrelated: https://github.com/lvgl/lvgl/commit/9b52db053122a0bfa2ea497a6516b9c546901538

File: src/lv_draw/lv_draw_rect.c (hunk 1 above)
Comment (embeddedt) [reply src/lv_draw/lv_draw_rect.c]: This would mean that pad == 0 and pad == -1 give the same result. Is that intended?

**Comment by embeddedt** [comment]
It's possible that GitHub updated the compiler version. For now I'd suggest adding `-Wno-error=cast-function-type`, since thus far this code hasn't caused problems.

File: src/lv_draw/lv_draw_rect.c (hunk 1 above)
Comment (kisvegabor) [reply src/lv_draw/lv_draw_rect.c]: Yes, I think it's better to make some inconsistency on edge cases than on all cases. E.g. with your original suggestion, border_width = 2 and outline_width = 2 would result in different widths very close to each other.

Or maybe it'd be even better to no change the width at all. We can say that pad=0 means on the edge.

**Comment by kisvegabor** [comment]
Added. It solved the issue.

File: src/lv_draw/lv_draw_rect.c (hunk 1 above)
Comment (embeddedt) [reply src/lv_draw/lv_draw_rect.c]: I think they both have to be changed together, otherwise the switch border looks a lot smaller than it should, so I went with your original suggestion (change only when pad == 0).

**Comment by embeddedt** [comment]
I've just realized that the build was probably broken by https://github.com/lvgl/lvgl/commit/a62ecda7607c73093411f4d498857252c7c3b304#diff-a162b5fe66656b8142afe7364fb36a1f096d88400a33edb957a7859400769f42R40.

**Comment by kisvegabor** [comment]
Actually it seems reasonable that a function is incompatible if an argument is `int16_t` instead of `int32_t` because only 2 bytes are passed to the stack but 4 bytes are read and therefore 2 bytes can be garbage. 

I suggest changing typedef back to `lv_coord_t`. 

cc @xiaoxiang781216

**Comment by embeddedt** [comment]
As the build failure is not caused by this PR, is it ready to be merged?

**Comment by kisvegabor** [comment]
Sure! Thanks!
