### PR TITLE
fix(ffmpeg): fix ffmpeg decoder assert

### LINKED ISSUE #8108: ffmpeg `lv_image_set_src()` broken by PR #7969
### LVGL version

v9.2.0-748-g8da142549

### Platform

WSL

### What happened?

Running this code:

```cpp
lv_obj_t* image = lv_image_create(cont);
lv_image_set_src(image, "A:assets/ffmpeg.png");
```

With `LV_USE_FFMPEG=1` and `LV_USE_LIBPNG=0` in `lv_conf.h`

The code fails the assertion added by PR #7969 in `lv_image_decoder_open()`

```
/*
     * We assume that if a decoder can get the info, it can open the image.
     * If decoder open failed, free the source and return error.
     * If decoder open succeed, add the image to cache if enabled.
     * */
    lv_result_t res = dsc->decoder->open_cb(dsc->decoder, dsc);

    if(res == LV_RESULT_OK && dsc->decoded != NULL) {
        LV_ASSERT_MSG(dsc->decoded->unaligned_data && dsc->decoded->handlers, "Invalid draw buffer");

        /* Flush the D-Cache if enabled and the image was successfully opened */
        if(dsc->args.flush_cache) {
            lv_draw_buf_flush_cache(dsc->decoded, NULL);
            LV_LOG_INFO("Flushed D-cache: src %p (%s) (W%d x H%d, data: %p cf: %d)",
                        src,
                        dsc->src_type == LV_IMAGE_SRC_FILE ? (const char *)src : "c-array",
                        dsc->decoded->header.w,
                        dsc->decoded->header.h,
                        (void *)dsc->decoded->data,
                        dsc->decoded->header.cf);
        }
    }

    return res;
```

`LV_ASSERT_MSG(dsc->decoded->unaligned_data && dsc->decoded->handlers, "Invalid draw buffer");` fails because `unaligned_data` is set to `NULL` by ffmpeg in `decoder_open()`. `handlers` is also `NULL`

If this assert is removed then the image is displayed correctly. Otherwise the code enters an infinitely while loop.

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by FASTSHIFT**
Fixes https://github.com/lvgl/lvgl/issues/8108

1. Fix ASSERT caused by improper `draw_buf` settings.
2. Fix example.
3. Add test cases for image and video decoding. (Version: [FFmpeg 6.1.2 "Heaviside"](https://www.ffmpeg.org/releases/ffmpeg-6.1.2.tar.xz))

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — DISMISSED** [review]
Thank you! It's great that we have tests for it now.

File: tests/src/test_cases/libs/test_ffmpeg.c [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+    TEST_ASSERT_MEM_LEAK_LESS_THAN(mem_before, 32);
+
+    /* Re-add other decoder */
+#if LV_USE_LODEPNG
+    lv_lodepng_deinit();
+#endif
+
+#if LV_USE_LIBPNG
+    lv_libpng_deinit();
+#endif
```
Comment (liamHowatt) [inline tests/src/test_cases/libs/test_ffmpeg.c]: Meant to be `..._init` I think.

**Review by liamHowatt — COMMENTED** [review]
Fantastic, thank you! Thanks for enforcing the `USE_LV_FS` requirement for the image example.

File: tests/src/test_cases/libs/test_ffmpeg.c (hunk 1 above)
Comment (FASTSHIFT) [reply tests/src/test_cases/libs/test_ffmpeg.c]: Nice catch!

**Review by liamHowatt — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
