### PR TITLE
fix(image): set the draw_task area correctly for tiled image

### LINKED ISSUE #6025: Moving wallpaper test from benchmark wrong coordinates
### LVGL version

v9.1.0

### What happened?

During testing we found that the area that is saved in the draw task for the moving wallpaper test is the area of just the image and not the area of the whole rectangle on which the image should be placed. 
image

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by kisvegabor**
fixes #6025

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by FASTSHIFT — DISMISSED** [review]

**Comment by kisvegabor** [comment]
FYI, it was an issue during dependency checking with multiple draw units too. As only a single tile was considered as the area of the draw tasks, other widgets for overlapping during rendering. We have checked that this issue is also resolved.

File: src/draw/lv_draw_image.h [hunk 1]
```diff
@@ -59,9 +59,11 @@ typedef struct _lv_draw_image_dsc_t {
     uint16_t tile               : 1;
     lv_draw_image_sup_t * sup;
 
-    /** Might be used to indicate the original size of the image if only a small portion is rendered now.
-     * Used when a part of a layer is rendered to show the total layer size*/
-    lv_area_t original_area;
+    /** Used to indicate the original position size of the image.
+     * It's important for
+     *  1. layer rendering where it might happen the only a smaller area of the layer is rendered.
+     *  2. tiled images where the target draw area is larger then the image to tile.*/
```
Comment (XuNeo) [inline src/draw/lv_draw_image.h]: Hope I understand it correctly. What does the `original` here mean? 
```suggestion
/** Used to indicate the entire original, non-clipped area where the image is to be drawn.
 * This is important for:
 *  1. Layer rendering, where it might happen that only a smaller area of the layer is rendered.
 *  2. Tiled images, where the target draw area is larger than the image to be tiled.
 */
```

Comment (kisvegabor) [reply src/draw/lv_draw_image.h]: Yes, it's correct! Your version is cleaner :slightly_smiling_face:

**Comment by nicusorcitu** [comment]
Hi @kisvegabor, the fix works on our side.
@FASTSHIFT @XuNeo can you please review and integrate the patch?
Thanks.

**Review by XuNeo — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]
