### PR TITLE
fix(freertos): notifiy-based sync can be initialized from any task

### LINKED ISSUE #6414: lv_timer_handler hangs when running on separate thread on ESP32 using FREERTOS using Arduino framework
### LVGL version

9.1.0

### What happened?

When I call lv_timer_handler from the main loop (with or without a mutex protection everything works.

When I create a separate thread using xTaskCreatePinnedToCore (on either core) with or without a mutex protection and this task calls the method lv_timer_handler this method never returns (it actually hangs in: refr_invalid_areas(); which again hangs in: lv_thread_sync_wait(&_draw_info.sync); in the lv_draw.c file.

### How to reproduce?

//This is the task definition:
void ProcessDisplay(void *arg)
{
    ESP_LOGD(TAG, "Starting LVGL task");

    uint32_t task_delay_ms = LVGL_PORT_TASK_MAX_DELAY_MS;
    while (1) {
        lv_mutex_lock(&lvgl_mutex);
        task_delay_ms = lv_timer_handler(); 
        lv_mutex_unlock(&lvgl_mutex);
        if (task_delay_ms > LVGL_PORT_TASK_MAX_DELAY_MS) {
            task_delay_ms = LVGL_PORT_TASK_MAX_DELAY_MS;
        } else if (task_delay_ms < LVGL_PORT_TASK_MIN_DELAY_MS) {
            task_delay_ms = LVGL_PORT_TASK_MIN_DELAY_MS;
        }
        vTaskDelay(pdMS_TO_TICKS(task_delay_ms));
    }
}

// Mutex is created like this:
lv_mutex_init(&lvgl_mutex);                         // Make lvgl thread safe

// This is how the task is created
BaseType_t ret = xTaskCreatePinnedToCore(ProcessDisplay, "lvgl", LVGL_PORT_TASK_STACK_SIZE, NULL,
                                                                               LVGL_PORT_TASK_PRIORITY, &lvgl_task_handle, core_id);
// where stack size is 6k bytes, the piority is 2

Note that this only happens if I define:
#define LV_USE_OS   LV_OS_FREERTOS
in lv_conf.h

When I define this as LV_OS_NONE it all works.

Should I not set this LV_USE_OS to LV_OS_FREERTOS when using ESP32 on framwork Arduino which is running on top of the FreeRTOS???

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

Fixes #6414

`lv_thread_sync_wait` can be called from a thread other than the one that called `lv_thread_sync_init`.

@nicusorcitu

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
cc @espzav @Jvsjvs

**Review by kisvegabor — DISMISSED** [review]
Thank you Liam! 

I wonder if other operating systems don't have the same issue. 

Anyway, I've looked into LVGL and couldn't see an obvious way to restructure it to make it work even without this fix. So I suggest merging this fix now and see if the issue shows up for others too.

**Comment by Jvsjvs** [comment]
Thanks for picking it up. 

If there is a performance hit, then I believe it is better to simply enforce the users to use the same thread with proper documentation. 

This restriction is easy to address by the users, maybe you can propose to the users to use a similar setup as I did and documented in the original issue.

If it works now without performance hit then this is of course perfect!!

File: src/osal/lv_freertos.c [hunk 1]
```diff
@@ -261,8 +272,19 @@ lv_result_t lv_thread_sync_wait(lv_thread_sync_t * pxCond)
...
+    _enter_critical();
+    TaskHandle_t task_to_notify = pxCond->xTaskToNotify;
+    pxCond->xTaskToNotify = NULL;
+    if(task_to_notify == NULL) {
+        /* No task waiting to be notified. Send this signal for later */
+        pxCond->xSignalSent = pdTRUE;
+    }
+    _exit_critical();
+
+    if(task_to_notify != NULL) {
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:284]: Please use the freertos naming convention: rename `task_to_notify` to 'xTaskToNotify`:

https://www.freertos.org/Documentation/02-Kernel/06-Coding-guidelines/02-FreeRTOS-Coding-Standard-and-Style-Guide#naming-conventions

File: src/osal/lv_freertos.c [hunk 2]
```diff
@@ -194,10 +194,21 @@ lv_result_t lv_thread_sync_wait(lv_thread_sync_t * pxCond)
     lv_result_t lvRes = LV_RESULT_OK;
 
 #if USE_FREERTOS_TASK_NOTIFY
-    LV_UNUSED(pxCond);
+    TaskHandle_t current_task_handle = xTaskGetCurrentTaskHandle();
+
+    _enter_critical();
+    BaseType_t signal_sent = pxCond->xSignalSent;
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:200]: Please use the freertos naming convention: rename `signal_sent` to 'xSignalSent`

**Comment by nicusorcitu** [comment]
@liamHowatt thanks for this PR.

**Review by nicusorcitu — APPROVED** [review]

File: src/osal/lv_freertos.c [hunk 3]
```diff
@@ -194,10 +194,21 @@ lv_result_t lv_thread_sync_wait(lv_thread_sync_t * pxCond)
     lv_result_t lvRes = LV_RESULT_OK;
 
 #if USE_FREERTOS_TASK_NOTIFY
-    LV_UNUSED(pxCond);
+    TaskHandle_t current_task_handle = xTaskGetCurrentTaskHandle();
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:197]: `xCurrentTaskHandle`

File: src/osal/lv_freertos.c [hunk 4]
```diff
@@ -261,8 +272,19 @@ lv_result_t lv_thread_sync_wait(lv_thread_sync_t * pxCond)
 lv_result_t lv_thread_sync_signal(lv_thread_sync_t * pxCond)
 {
 #if USE_FREERTOS_TASK_NOTIFY
-    /* Send a notification to the task waiting. */
-    xTaskNotifyGive(pxCond->xTaskToNotify);
+    _enter_critical();
+    TaskHandle_t task_to_notify = pxCond->xTaskToNotify;
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:276]: Use the new member `BaseType_t    xIsInitialized; ` to verify if the task to notify is valid.

File: src/osal/lv_freertos.h [hunk 5]
```diff
@@ -63,6 +63,7 @@ typedef struct {
 typedef struct {
 #if USE_FREERTOS_TASK_NOTIFY
     TaskHandle_t xTaskToNotify;
+    BaseType_t xSignalSent;
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.h]: Please use the freertos naming convention all over in this file:
https://www.freertos.org/Documentation/02-Kernel/06-Coding-guidelines/02-FreeRTOS-Coding-Standard-and-Style-Guide#naming-conventions

At a better look, I think you can use a member like 
`BaseType_t    xIsInitialized; `
similar as it is done on semaphore implementation.

E.G. no signal can be done until the initialization is done.

File: src/osal/lv_freertos.c [hunk 6]
```diff
@@ -179,8 +179,8 @@ lv_result_t lv_mutex_delete(lv_mutex_t * pxMutex)
 lv_result_t lv_thread_sync_init(lv_thread_sync_t * pxCond)
 {
 #if USE_FREERTOS_TASK_NOTIFY
-    /* Store the handle of the calling task. */
-    pxCond->xTaskToNotify = xTaskGetCurrentTaskHandle();
+    pxCond->xTaskToNotify = NULL;
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c]: Please don't remove the scope of the init API.

Add a local function here like:
```
    /* If the cond is uninitialized, perform initialization. */
    prvCheckCondInit(pxCond);
```
and let the initialization happen if it get called explicitly.

Then make use of the same static function `prvCheckCondInit(pxCond);` in the `lv_thread_sync_wait()`.

**Review by nicusorcitu — CHANGES_REQUESTED** [review]

**Comment by liamHowatt** [comment]
Thanks for the review!

File: src/osal/lv_freertos.h [hunk 7]
```diff
@@ -51,7 +51,7 @@ extern "C" {
 
 typedef struct {
     void (*pvStartRoutine)(void *);       /**< Application thread function. */
-    void * xTaskArg;                      /**< Arguments for application thread function. */
+    void * pTaskArg;                      /**< Arguments for application thread function. */
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.h:54]: `pvTaskArg`

File: src/osal/lv_freertos.h [hunk 8]
```diff
@@ -61,11 +61,12 @@ typedef struct {
 } lv_mutex_t;
 
 typedef struct {
+    BaseType_t
+    xIsInitialized;                       /**< Set to pdTRUE if this condition variable is initialized, pdFALSE otherwise. */
 #if USE_FREERTOS_TASK_NOTIFY
     TaskHandle_t xTaskToNotify;
+    BaseType_t xSignalSent;
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.h]: No need for `xSignalSent`, so it can be removed, correct? We make use of the `pxCond->xSyncSignal` now.

File: src/osal/lv_freertos.c [hunk 9]
```diff
@@ -396,9 +423,12 @@ static void prvCheckMutexInit(lv_mutex_t * pxMutex)
     }
 }
 
-#if !USE_FREERTOS_TASK_NOTIFY
 static void prvCondInit(lv_thread_sync_t * pxCond)
 {
+#if USE_FREERTOS_TASK_NOTIFY
+    pxCond->xTaskToNotify = NULL;
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:438]: Implement this, similar as it is done for semaphores.
I see it like:
```
#if USE_FREERTOS_TASK_NOTIFY
    pxCond->xTaskToNotify = xTaskGetCurrentTaskHandle();
    pxCond->xIsInitialized = pdTRUE;
    pxCond->xSyncSignal = pdFALSE;
#else
```
You might have the last two common for semaphores and sygnal thread.

File: src/osal/lv_freertos.c [hunk 10]
```diff
@@ -396,9 +423,12 @@ static void prvCheckMutexInit(lv_mutex_t * pxMutex)
...
+    pxCond->xSignalSent = pdFALSE;
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:430]: Use `pxCond->xSyncSignal = pdFALSE;` instead

File: src/osal/lv_freertos.c [hunk 11]
```diff
@@ -260,13 +266,24 @@ lv_result_t lv_thread_sync_wait(lv_thread_sync_t * pxCond)
...
 {
-#if USE_FREERTOS_TASK_NOTIFY
-    /* Send a notification to the task waiting. */
-    xTaskNotifyGive(pxCond->xTaskToNotify);
-#else
     /* If the cond is uninitialized, perform initialization. */
     prvCheckCondInit(pxCond);
 
+#if USE_FREERTOS_TASK_NOTIFY
+    _enter_critical();
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:275]: Replace all new code with:
```
#if USE_FREERTOS_TASK_NOTIFY
    xTaskNotifyGive(pxCond->xTaskToNotify);
    pxCond->xSyncSignal = pdTRUE;
#else
```

File: src/osal/lv_freertos.c [hunk 12]
```diff
@@ -193,17 +188,28 @@ lv_result_t lv_thread_sync_wait(lv_thread_sync_t * pxCond)
 {
     lv_result_t lvRes = LV_RESULT_OK;
 
+    /* If the cond is uninitialized, perform initialization. */
+    prvCheckCondInit(pxCond);
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:192]: If wait gets called prior of any init, this call will do the initialization.

File: src/osal/lv_freertos.c [hunk 13]
```diff
@@ -193,17 +188,28 @@ lv_result_t lv_thread_sync_wait(lv_thread_sync_t * pxCond)
...
+
 #if USE_FREERTOS_TASK_NOTIFY
-    LV_UNUSED(pxCond);
+    TaskHandle_t current_task_handle = xTaskGetCurrentTaskHandle();
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:195]: Replace all new code with:
```
#if USE_FREERTOS_TASK_NOTIFY
    while(!pxCond->xSyncSignal) {
        ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
    }
    pxCond->xSyncSignal = pdFALSE;
#else
````

File: src/osal/lv_freertos.c [hunk 14]
```diff
@@ -304,31 +321,41 @@ lv_result_t lv_thread_sync_signal(lv_thread_sync_t * pxCond)
...
-    /* Send a notification to the task waiting. */
-    vTaskNotifyGiveFromISR(pxCond->xTaskToNotify, &xHigherPriorityTaskWoken);
-    portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
-#else
+
     /* If the cond is uninitialized, perform initialization. */
     prvCheckCondInit(pxCond);
 
+#if USE_FREERTOS_TASK_NOTIFY
+    _enter_critical();
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:348]: Similar as done for sync_signal.

**Review by nicusorcitu — CHANGES_REQUESTED** [review]

File: src/osal/lv_freertos.h (hunk 7 above)
Comment (liamHowatt) [reply src/osal/lv_freertos.h:54]: In the coding standard naming conventions you linked, the "v" seems to only apply for function names that return `void` (nothing), not void pointer variables.

File: src/osal/lv_freertos.h (hunk 8 above)
Comment (liamHowatt) [reply src/osal/lv_freertos.h]: Not currently, but I can make that variable common between both implementations :+1:

File: src/osal/lv_freertos.c (hunk 12 above)
Comment (liamHowatt) [reply src/osal/lv_freertos.c:192]: Correct. I applied your feedback after your last review to make it work that way. Is there something you want me to change?

File: src/osal/lv_freertos.c (hunk 13 above)
Comment (liamHowatt) [reply src/osal/lv_freertos.c:195]: I'm not completely clear on this. Is this a different solution?

Comment (nicusorcitu) [reply src/osal/lv_freertos.c:195]: I mean to replace all the code under `#if USE_FREERTOS_TASK_NOTIFY` with the above suggestion and see if it works to you.

File: src/osal/lv_freertos.c (hunk 11 above)
Comment (nicusorcitu) [reply src/osal/lv_freertos.c:275]: I mean to replace all the code under `#if USE_FREERTOS_TASK_NOTIFY` with the above suggestion and see if it works to you.

File: src/osal/lv_freertos.c (hunk 9 above)
Comment (nicusorcitu) [reply src/osal/lv_freertos.c:438]: I mean to replace all the code under `#if USE_FREERTOS_TASK_NOTIFY` with the above suggestion and see if it works to you.

**Comment by liamHowatt** [comment]
> I mean to replace all the code under `#if USE_FREERTOS_TASK_NOTIFY` with the above suggestion and see if it works to you.

Gotcha, I will have time to try tomorrow.

**Comment by liamHowatt** [comment]
Yes, it is currently working.

**Review by kisvegabor — APPROVED** [review]

**Comment by kisvegabor** [comment]
Thanks, merging then to make sure that it's fixed in v9.2.

File: src/osal/lv_freertos.c (hunk 11 above)
Comment (liamHowatt) [reply src/osal/lv_freertos.c:275]: > Replace all new code with:
> 
> ```
> #if USE_FREERTOS_TASK_NOTIFY
>     xTaskNotifyGive(pxCond->xTaskToNotify);
>     pxCond->xSyncSignal = pdTRUE;
> #else
> ```

`pxCond->xTaskToNotify` may be `NULL` which is why there is the current logic to determine which task to notify, if any.

**Review by liamHowatt — COMMENTED** [review]
I think you have a simpler way to do it than what I've done. Would you mind opening a PR? :slightly_smiling_face:

**Comment by nicusorcitu** [comment]
`prvCheckCondInit(pxCond);` should always make sure that `pxCond->xTaskToNotify` is not null, (e.g. the conditional wait is always initialized).

File: src/osal/lv_freertos.c [hunk 15]
```diff
@@ -304,31 +325,43 @@ lv_result_t lv_thread_sync_signal(lv_thread_sync_t * pxCond)
...
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:348]: `_enter_critical()` does not work for ISR, it will hang.
You would have to add new defines:
```
#define _enter_critical_isr() taskENTER_CRITICAL_FROM_ISR();
```

**Comment by nicusorcitu** [comment]
> I think you have a simpler way to do it than what I've done. Would you mind opening a PR? 🙂

We have a strict way of pushing commits to upstream, need to pass some additional checks.

For this particular issue we might send a commit with the proposal, will open a PR soon.
@cosmindanielradu19

File: src/osal/lv_freertos.c (hunk 15 above)
Comment (liamHowatt) [reply src/osal/lv_freertos.c:348]: Very good catch! :open_mouth: In all of the environments I've seen so far, the same critical section API is used inside and outside of ISRs. I tested on ESP32-S3 and it worked for me. Maybe only some ports of FreeRTOS implement the ISR version with important extra steps.

**Comment by nicusorcitu** [comment]
I have done a lot of tests and investigated the new code which does not seem to work anymore on FreeRTOS.
The whole story start from this sentence:
> lv_thread_sync_wait can be called from a thread other than the one that called lv_thread_sync_init.
>
But why? Task notification is different than semaphore implementation.
On semaphores there is a single sync that can be used in both directions.
On task notification you can use the sync only in a single direction. If you want to be both ways you will need two synchronizations, hence two init calls.

I would revert the changes due to this commit and revise it from the application level. It had more sense as it was before.

**Comment by liamHowatt** [comment]
Even after using the `taskENTER_CRITICAL_FROM_ISR` fix? Do you know what usage pattern causes the failure you're seeing? I would like to understand why these changes aren't working.

Please see the issue this PR is linked to https://github.com/lvgl/lvgl/issues/6414. It's non-obvious to users that the task that calls `lv_timer_handler` must be the same task that called `lv_init`. Vendor port code also made the mistake.

It seems like the task notify vs semaphore choice is not very configurable. It's a define in a header file, not part of the config. I think the task notify implementation has the potential to deprecate the semaphore implementation at some point, but only if it doesn't have too many tradeoffs. If both implementations stay, I think it should be easier for a user to choose which implementation they want.

**Comment by nicusorcitu** [comment]
> Even after using the taskENTER_CRITICAL_FROM_ISR fix?
>
Yes, that would fix only the hang from ISR.
Let's say Task1 is the LVGL and Task2 is the GPU unit.
Task1 have `_draw_info.sync` to know when it has to dispatch again.
Task2 have `u.sync` to know when to process a task.

As I mentioned in the previous comment, the task notification means that Task1 waits on `_draw_info.sync` and Task2 signals the Task1 Handle. So it works only in one direction.
Task2 waits on `u.sync` until a new task is passed to the unit and signaled from Task1.

1. In this PR you changed the behavior of what sync means. E.G. if Task2 signals before Task1 waits, then Task1 wait will just pass waiting.
And is fine, this case happens case Task2 have higher priority than Task1.

2. But, in dispatcher in Task1, while there is a need for Task2 to `wait_for_completion` it will signal Task2 and will return to dispatcher.
image
But during dispatching, there will be no wait at all because of the previous signal:
image
Hence, Task1 will get blocked on the steps: signal, wait, signal, wait, signal, wait.... on its own thread handle. So Task1 will never wait (because will just pass waiting as previously signaled), so Task1 will never sleep so never returned to scheduler to give the possibility to Task2 to wake up and complete his job.

I really suggest to revert back the change and I will add the config `LV_USE_TASK_NITOFICATION` under `LV_USE_FREETOS` to let it configurable by user.
If used want, he can switch back to the semaphores implementation.
If user want to stay with task notification then he need to be aware that task notification is unidirectional. It is what the name says.

**Comment by liamHowatt** [comment]
I'm looking at the code you're talking about. I think `lv_draw_dispatch_wait_for_request` will block the next time it's called. It should block until the next `lv_draw_dispatch_request`.

I don't think `lv_draw_dispatch_wait_for_request` will return immediately every time while being called in a loop. If the signal was already sent, yes, it will return immediately. But the next time it will block at `ulTaskNotifyTake` until another `lv_draw_dispatch_request` is called from Task2 (the GPU).

**Comment by nicusorcitu** [comment]
Exactly that is the case, the sync goes first then wait will return immediately. So It will create a loop in dispatcher.

All the user need to do is to keep in mind that the sync point means that the thread handle `pxCond->xTaskToNotify` is the task that waits. Any other task can signal it to unblock. This already is functioning on LVGL, there are 2 sync points for signaling in both direction:
> Let's say Task1 is the LVGL and Task2 is the GPU unit.
> Task1 have `_draw_info.sync` to know when it has to dispatch again.
> Task2 have `u.sync` to know when to process a task.

Please also see the example in FreeRTOS: https://www.freertos.org/Documentation/02-Kernel/04-API-references/05-Direct-to-task-notifications/01-xTaskNotifyGive

I will prepare a patch and will push it to github on PR https://github.com/lvgl/lvgl/pull/6793

**Comment by liamHowatt** [comment]
> Exactly that is the case, the sync goes first then wait will return immediately. So It will create a loop in dispatcher.

It would block at the next call, though. No? `xSyncSignal` is reset to `pdFALSE` so at most it can only return immediately once and then block the next time. How does it become and infinite loop?

```c
lv_result_t lv_thread_sync_wait(lv_thread_sync_t * pxCond)
{
    lv_result_t lvRes = LV_RESULT_OK;

    /* If the cond is uninitialized, perform initialization. */
    prvCheckCondInit(pxCond);

#if USE_FREERTOS_TASK_NOTIFY
    TaskHandle_t current_task_handle = xTaskGetCurrentTaskHandle();

    _enter_critical();
    BaseType_t signal_sent = pxCond->xSyncSignal;
    pxCond->xSyncSignal = pdFALSE;
    if(signal_sent == pdFALSE) {
        /* The signal hasn't been sent yet. Tell the sender to notify this task */
        pxCond->xTaskToNotify = current_task_handle;
    }
    /* If we have a signal from the other task, we should not ask to be notified */
    _exit_critical();

    if(signal_sent == pdFALSE) {
        /* Wait for other task to notify this task. */
        ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
    }
    /* If the signal was received, no wait needs to be done */
#else
    /* ... */
#endif

    return lvRes;
}
```

**Comment by nicusorcitu** [comment]
I will loop because the signal will always come first in this order: signal, wait, signal, wait, signal, wait....

**Comment by liamHowatt** [comment]
So it's not spinning in an infinite loop in one task. It's switching between tasks. What's wrong with signal, wait, signal, wait, signal, wait?

**Comment by liamHowatt** [comment]
It looks like draw drivers are supposed to provide a `wait_for_finish_cb` which is called in `lv_draw_wait_for_finish` to trigger the context switch if they have their own threads. Looks like vglite is the only one that has a `wait_for_finish_cb`. draw_sw doesn't have a `wait_for_finish_cb`. I think it's a bit strange that we are relying on the signal to always context switch even if the thread is signalling itself.

How did the old implementation work? How does a high priority task trigger a context switch to a lower priority task by sending a signal to itself?

File: src/osal/lv_freertos.c [hunk 16]
```diff
@@ -193,17 +188,30 @@ lv_result_t lv_thread_sync_wait(lv_thread_sync_t * pxCond)
...
+    BaseType_t signal_sent = pxCond->xSyncSignal;
+    pxCond->xSyncSignal = pdFALSE;
+    if(signal_sent == pdFALSE) {
+        /* The signal hasn't been sent yet. Tell the sender to notify this task */
+        pxCond->xTaskToNotify = current_task_handle;
+    }
+    /* If we have a signal from the other task, we should not ask to be notified */
+    _exit_critical();
+
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:206]: After exiting from critical section the `pxCond->xSyncSignal` might get changed, so this is not thread safe.

File: src/osal/lv_freertos.c [hunk 17]
```diff
@@ -260,13 +268,26 @@ lv_result_t lv_thread_sync_wait(lv_thread_sync_t * pxCond)
...
+    _enter_critical();
+    TaskHandle_t task_to_notify = pxCond->xTaskToNotify;
+    pxCond->xTaskToNotify = NULL;
+    if(task_to_notify == NULL) {
+        /* No task waiting to be notified. Send this signal for later */
+        pxCond->xSyncSignal = pdTRUE;
+    }
+    /* If a task is already waiting, there is no need to set the sync signal */
+    _exit_critical();
+
```
Comment (nicusorcitu) [inline src/osal/lv_freertos.c:284]: Same here, you exit from critical section but still rely on the `task_to_notify`. Not thread safe.

**Comment by nicusorcitu** [comment]
@cosmindanielradu19 @cristian-stoica 
This PR generated another task synchronization issue with both VGLite and PXP screen rotation enabled.
I still believe we should get back to the original implementation where a single task can wait and a single task can signal.
>>I really suggest to revert back the change and I will add the config LV_USE_TASK_NOTIFICATION under LV_USE_FREETOS to let it configurable by user.
If used want, he can switch back to the semaphores implementation.
If user want to stay with task notification then he need to be aware that task notification is unidirectional. It is what the name says.
>>

**Comment by kisvegabor** [comment]
@nicusorcitu Please open a PR to see the proposed changes. @liamHowatt, you were more involved into this issue, please take a look.

**Comment by nicusorcitu** [comment]
I do not have a fix yet, neither time to look at it right now. But I will try a patch till 20Dec. I will let you know both about it.

**Comment by liamHowatt** [comment]
I would like to understand what's wrong with the fix I did. You raised some concerns in the PR during review. Can you reiterate the ones that you still believe are potential causes of instability? I truly believe the parts you flagged as thread-unsafe are thread-safe. Can we begin reviewing those changes, starting with a specific bug?

**Comment by cristian-stoica** [comment]
@liamHowatt I'm looking at a situation when running lv_demo_benchmark with both VGLITE and PXP enabled (SW draw unit = 0). Tests run as expected until rotated_argb_image_cb when the screen turns black and app stops. Debugging shows the code is still running in a dispatch-execute loop without any progress at all.  I'm not sure what is actually going on. What I've also tried is disabling TASK_NOTIFY and the application runs. I can reproduce the issue only by running only that test under MCUX from flash (LVGL 9.2.1).
It's strange because I've had reproducibility issues when running the project built with different compilers IAR, MCUX and running under debugger (no breakpoints) or without it.

**Comment by nicusorcitu** [comment]
The issue we see works just fine with semaphore implementation. It hangs only if we use `LV_USE_FREERTOS_TASK_NOTIFY`.

>> I truly believe the parts you flagged as thread-unsafe are thread-safe. Can we begin reviewing those changes, starting with a specific bug?
>>

```
lv_result_t lv_thread_sync_wait(lv_thread_sync_t * pxCond)
{
    lv_result_t lvRes = LV_RESULT_OK;

    /* If the cond is uninitialized, perform initialization. */
    prvCheckCondInit(pxCond);

#if LV_USE_FREERTOS_TASK_NOTIFY
    TaskHandle_t xCurrentTaskHandle = xTaskGetCurrentTaskHandle();

    _enter_critical();
    BaseType_t xSyncSygnal = pxCond->xSyncSignal; ---> This might be TRUE
    pxCond->xSyncSignal = pdFALSE; ---> Becoming FALSE
    if(xSyncSygnal == pdFALSE) {
        /* The signal hasn't been sent yet. Tell the sender to notify this task */
        pxCond->xTaskToNotify = xCurrentTaskHandle;
    }
    /* If we have a signal from the other task, we should not ask to be notified */
    _exit_critical();

    if(xSyncSygnal == pdFALSE) { ---> Another Thread might just set pxCond->xSyncSignal = pdTRUE so this check might get wrong
        /* Wait for other task to notify this task. */
        ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
    }
    /* If the signal was received, no wait needs to be done */
#else
```

I will try to do some debugs but can't have right now, I will let you know when I have something.
