### PR TITLE
fix: warn user about deprecated LV_DEFAULT_DRIVE_LETTER

### LINKED ISSUE #7614: LVGL Docs deployment failed
### LVGL version

v9.2.0-388-g46ab31855

### Platform

CI

### What happened?

docs build break

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by AndreCostaaa**
Fixes #7614
 

Like explained here: https://github.com/lvgl/lvgl/issues/7614#issuecomment-2596408267

The line `#define LV_FS_DEFAULT_DRIVE_LETTER     LV_FS_DEFAULT_DRIVER_LETTER` is causing the docs generation workflow to crash when building the examples because of a symbol redefinition. This checks if the symbol is already defined to avoid redefining it

### CODE REVIEW

**Review by uLipe — DISMISSED** [review]

**Comment by XuNeo** [comment]
Maybe it's better to fix `/home/runner/work/lvgl/lvgl/emscripten_builder/lv_conf.h:793:9` to use correct macro?

**Comment by liamHowatt** [comment]
There are three reasons the docs build is failing. I fixed it in this PR: https://github.com/lvgl/lv_web_emscripten/pull/26 :slightly_smiling_face:

This is an important PR in general, I think.

**Comment by AndreCostaaa** [comment]
Nice one! We can close this one then

**Comment by AndreCostaaa** [comment]
> This is an important PR in general, I think.

I don't follow. In what sense is it important?

**Comment by liamHowatt** [comment]
When that config got renamed, there were two mechanisms added both trying to solve the same problem. This line in the API map, and the below.

https://github.com/lvgl/lvgl/blob/05a0395a1c2f1b36d58ebd247f9582a0e4638bb4/scripts/lv_conf_internal_gen.py#L91-L94

I don't feel great about either. I think maybe the one in `lv_conf_internal_gen.py` could go away, and the one in `lv_api_map_v9_1.h` could become

```c
#ifdef LV_FS_DEFAULT_DRIVE_LETTER
#error deprecate config name. Rename to LV_FS_DEFAULT_DRIVER_LETTER
#endif
```

but that's just a 30 second idea. Open to any ideas whatsoever.

**Comment by AndreCostaaa** [comment]
On one hand I understand the idea of keeping backwards compatibility. On the other hand, the fact that the internal generation script got changed to add this feels a bit hacky imo

Also, I think that the user should at least get a warning if they're using a deprecated config. What do you think of removing this :
https://github.com/lvgl/lvgl/blob/05a0395a1c2f1b36d58ebd247f9582a0e4638bb4/scripts/lv_conf_internal_gen.py#L91-L94

And redefining it while providing a `#warning` inside `lv_api_map_v9_1.h` instead ?
Something like:
```c
#ifdef LV_FS_DEFAULT_DRIVE_LETTER
    #define LV_FS_DEFAULT_DRIVER_LETTER LV_FS_DEFAULT_DRIVE_LETTER
    #warning deprecate config name. Rename to LV_FS_DEFAULT_DRIVER_LETTER
#endif
```

File: src/lv_api_map_v9_1.h [hunk 1]
```diff
@@ -81,7 +81,15 @@ extern "C" {
 #define lv_chart_set_all_value lv_chart_set_all_values
 #define lv_calendar_set_showed_date lv_calendar_set_month_shown
 
+
+#if !defined(LV_FS_DEFAULT_DRIVER_LETTER) && defined(LV_FS_DEFAULT_DRIVE_LETTER)
```
Comment (liamHowatt) [inline src/lv_api_map_v9_1.h]: Argh, `LV_FS_DEFAULT_DRIVER_LETTER` will never not be defined at this point, since `lv_conf_internal.h` will define it, if it's not defined, so this will be unreachable.

**Review by liamHowatt — COMMENTED** [review]
Thanks for doing this.

File: src/lv_api_map_v9_1.h (hunk 1 above)
Comment (AndreCostaaa) [reply src/lv_api_map_v9_1.h]: So I guess I have to add this back to generation script :thinking:

Comment (AndreCostaaa) [reply src/lv_api_map_v9_1.h]: Or we could check if it equals '\0' as it would mean it got defined with its default value

File: src/lv_api_map_v9_1.h [hunk 2]
```diff
@@ -81,7 +81,15 @@ extern "C" {
 #define lv_chart_set_all_value lv_chart_set_all_values
 #define lv_calendar_set_showed_date lv_calendar_set_month_shown
 
-#define LV_FS_DEFAULT_DRIVE_LETTER     LV_FS_DEFAULT_DRIVER_LETTER
+#if defined(LV_FS_DEFAULT_DRIVE_LETTER)
+#warning LV_FS_DEFAULT_DRIVE_LETTER is deprecated. Rename to LV_FS_DEFAULT_DRIVER_LETTER
+
+#if LV_FS_DEFAULT_DRIVER_LETTER == '\0'
+#define LV_FS_DEFAULT_DRIVER_LETTER LV_FS_DEFAULT_DRIVE_LETTER
```
Comment (liamHowatt) [inline src/lv_api_map_v9_1.h:89]:
```suggestion
#undef LV_FS_DEFAULT_DRIVER_LETTER
#define LV_FS_DEFAULT_DRIVER_LETTER LV_FS_DEFAULT_DRIVE_LETTER
```

Undef first to avoid "`warning: "LV_FS_DEFAULT_DRIVER_LETTER" redefined`" unless you think it's good to have.

**Review by liamHowatt — COMMENTED** [review]
I think this must be close to the best solution. Thanks. I think that `'\0'` check is a really good idea.

File: src/lv_api_map_v9_1.h (hunk 2 above)
Comment (AndreCostaaa) [reply src/lv_api_map_v9_1.h:89]: It would probably cause too much confusion so I agree it's better to add the undef clause

**Review by liamHowatt — APPROVED** [review]

**Review by uLipe — APPROVED** [review]
