### PR TITLE
fix(label): do not break last line for LV_LABEL_LONG_DOT (#5606) (#6362)

### LINKED ISSUE #8335: Label Chinese display exception
### LVGL version

v8.4.1

### Platform

Emulator used verification.
Please refer to the phenomenon picture.
Here's the code.

LV_FONT_DECLARE(lv_font_32)
    lv_obj_t* obj = lv_obj_create(lv_scr_act());
    lv_obj_set_size(obj, width, height);
    lv_obj_set_style_bg_opa(obj, LV_OPA_100, LV_PART_MAIN);
    lv_obj_set_style_bg_color(obj, lv_color_black(), LV_PART_MAIN);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN);
    lv_obj_set_style_radius(obj, 0, LV_PART_MAIN);

    lv_obj_t *label = lv_label_create(obj);
	lv_obj_align(label, LV_ALIGN_CENTER, 0, 0);
	lv_obj_set_size(label, 242, 44);
	lv_label_set_long_mode(label, LV_LABEL_LONG_DOT);
	lv_obj_set_style_text_font(label, &lv_font_32, LV_PART_MAIN);
	lv_obj_set_style_text_color(label, lv_color_white(), LV_PART_MAIN);
	lv_label_set_text(label, "我你dK1!@#$%%.mp3");
    lv_obj_set_style_bg_opa(label, LV_OPA_100, LV_PART_MAIN);
    lv_obj_set_style_bg_color(label, lv_color_hex(0xff0000), LV_PART_MAIN);

	label = lv_label_create(obj);
	lv_obj_align(label, LV_ALIGN_CENTER, 0, 100);
	lv_obj_set_size(label, 242, 44);
	lv_label_set_long_mode(label, LV_LABEL_LONG_DOT);
	lv_obj_set_style_text_font(label, &lv_font_32, LV_PART_MAIN);
	lv_obj_set_style_text_color(label, lv_color_white(), LV_PART_MAIN);
	lv_label_set_text(label, "1234你56789dadd");
    lv_obj_set_style_bg_opa(label, LV_OPA_100, LV_PART_MAIN);
    lv_obj_set_style_bg_color(label, lv_color_hex(0xff0000), LV_PART_MAIN);

### What happened?

Image

### How to reproduce?

lv_font_32.c is generated by https://lvgl.io/tools/fontconverter, the Range: 0x20-0x7F,0x4F60,0x6211,0x4ED6

### PR DESCRIPTION
**Pull request by kisvegabor**
Fixes #8335 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by AndreCostaaa — DISMISSED** [review]

File: src/misc/lv_txt.c [hunk 1]
```diff
@@ -164,13 +164,11 @@ void lv_txt_get_size(lv_point_t * size_res, const char * text, const lv_font_t *
...
  * @param[out] word_w_ptr width (in pixels) of the parsed word. May be NULL.
- * @param cmd_state pointer to a txt_cmd_state_t variable which stores the current state of command processing
- * @param force Force return the fraction of the word that can fit in the provided space.
  * @return the index of the first char of the next word (in byte index not letter index. With UTF-8 they are different)
  */
 static uint32_t lv_txt_get_next_word(const char * txt, const lv_font_t * font,
-                                     lv_coord_t letter_space, lv_coord_t max_width,
-                                     lv_text_flag_t flag, uint32_t * word_w_ptr, lv_text_cmd_state_t * cmd_state, bool force)
+                                     int32_t letter_space, int32_t max_width,
+                                     lv_text_flag_t flag, uint32_t * word_w_ptr, lv_text_cmd_state_t * cmd_state)
```
Comment (liamHowatt) [inline src/misc/lv_txt.c]: Don't remove the `force` doc comment line

File: tests/src/test_cases/test_label.c [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+{
+    active_screen = lv_scr_act();
+    label = lv_label_create(active_screen);
+    long_label = lv_label_create(active_screen);
+    long_label_multiline = lv_label_create(active_screen);
+    empty_label = lv_label_create(active_screen);
+
+    lv_label_set_text(long_label, long_text);
+    lv_label_set_text(long_label_multiline, long_text_multiline);
+    lv_label_set_text(empty_label, empty_text);
```
Comment (liamHowatt) [inline tests/src/test_cases/test_label.c:29]: These are unused. Is it ok?

**Review by liamHowatt — COMMENTED** [review]
Otherwise LGTM

**Review by uLipe — DISMISSED** [review]
Besides @liamHowatt  point, LGTM as well.

File: src/misc/lv_txt.c (hunk 1 above)
Comment (kisvegabor) [reply src/misc/lv_txt.c]: `cmd_state` was missing, I've just added it.

File: src/widgets/lv_label.c [hunk 3]
```diff
@@ -329,6 +331,10 @@ void lv_label_get_letter_pos(const lv_obj_t * obj, uint32_t char_id, lv_point_t
 
     /*Search the line of the index letter*/;
     while(txt[new_line_start] != '\0') {
+        new_line_start += _lv_txt_get_next_line(&txt[line_start], font, letter_space, max_w, NULL, flag);
```
[the remark this answers is not in the document]
Comment (liamHowatt) [reply src/widgets/lv_label.c:334]: > This call to `_lv_txt_get_next_line` is duplicated just two lines below, causing the loop index to advance twice per iteration. Remove the first invocation so that each iteration only advances once.

Is the AI on to something here?

**Review by liamHowatt — APPROVED** [review]

**Review by uLipe — APPROVED** [review]
