### PR TITLE
fix(pinyin): update candidates on the second letter too

### LINKED ISSUE #8057: [Pinyin IME]: only the first typed character triggers a candidate panel update
### LVGL version

v9.3.0 dev

### Platform

[lv_port_linux@2e44742](https://github.com/lvgl/lv_port_linux/tree/2e44742ad7043ca3f17c164ca4ba12fccef90e5c) with SDL2 backend.

### What happened?

The candidate panel doesn't update after typing the second character.

In fact, it seems that only the first typed character triggers an update to the candidate panel.

### How to reproduce?

> [!NOTE]
> You can easily reproduce this issue with [the first example in the documentation](https://docs.lvgl.io/master/details/auxiliary-modules/ime_pinyin.html#pinyin-ime-26-key-input).

- Type `n`, the candidate panel displaying words `那 哪 拿 內 南` (in source file: [L242](https://github.com/lvgl/lvgl/blob/e63f345feccb6e3d8f317566de7e450676053693/src/others/ime/lv_ime_pinyin.c#L242))
- Type `i` continuously, the candidate panel doesn't update to `你 妳 呢` (in source file: [L248](https://github.com/lvgl/lvgl/blob/e63f345feccb6e3d8f317566de7e450676053693/src/others/ime/lv_ime_pinyin.c#L248))

### PR DESCRIPTION
**Pull request by kisvegabor**
fixes #8057

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by liamHowatt — DISMISSED** [review]
It works because it always invalidates even if the flag wasn't present?

File: src/others/ime/lv_ime_pinyin.c [hunk 1]
```diff
@@ -797,7 +797,9 @@ static void pinyin_input_proc(lv_obj_t * obj)
         }
     }
 
-    lv_obj_remove_flag(pinyin_ime->cand_panel, LV_OBJ_FLAG_HIDDEN);
+
+    pinyin_ime->cand_panel->flags &= (~LV_OBJ_FLAG_HIDDEN);
```
Comment (kisvegabor) [inline src/others/ime/lv_ime_pinyin.c]:
```suggestion
    lv_obj_remove_flag(pinyin_ime->cand_panel, LV_OBJ_FLAG_HIDDEN);
```

**Comment by kisvegabor** [comment]
I've just updated my code a little. So the problem was that the map of the button matrix was updated manually by just changing pointers. To make it visible an invalidation is required, however `lv_obj_remove_flag(obj, LV_OBJ_FLAG_HIDDEN)` won't invalidate an already visible item.

File: src/others/ime/lv_ime_pinyin.c [hunk 2]
```diff
@@ -797,7 +797,9 @@ static void pinyin_input_proc(lv_obj_t * obj)
         }
     }
 
+
```
Comment (kisvegabor) [inline src/others/ime/lv_ime_pinyin.c]:
```suggestion
```

File: src/others/ime/lv_ime_pinyin.c [hunk 3]
```diff
@@ -798,6 +798,7 @@ static void pinyin_input_proc(lv_obj_t * obj)
     }
 
     lv_obj_remove_flag(pinyin_ime->cand_panel, LV_OBJ_FLAG_HIDDEN);
+    lv_obj_invalidate(pinyin_ime->cand_panel);
```
Comment (liamHowatt) [inline src/others/ime/lv_ime_pinyin.c:801]: I see you made it easier to read, at the cost of potentially calling `lv_obj_invalidate` twice :wink:

What if you did this?

```suggestion
    if(lv_obj_has_flag(pinyin_ime->cand_panel, LV_OBJ_FLAG_HIDDEN)) {
        lv_obj_remove_flag(pinyin_ime->cand_panel, LV_OBJ_FLAG_HIDDEN);
    }
    else {
        lv_obj_invalidate(pinyin_ime->cand_panel);
    }
```

Comment (kisvegabor) [reply src/others/ime/lv_ime_pinyin.c:801]: The invalidation is cheap and if an area is already invalidated it will be filtered out anyway. So I'd keep it as it is for code simplicity.

Comment (liamHowatt) [reply src/others/ime/lv_ime_pinyin.c:801]: Okay I agree

**Review by liamHowatt — APPROVED** [review]

**Comment by kisvegabor** [comment]
The failing CI is unrelated

**Review by AndreCostaaa — APPROVED** [review]
Makes sense :rocket:
