### PR TITLE
fix(label): consider max-width

### LINKED ISSUE #5636: Label text doesn't wrap according to `max_width`
### LVGL version

v9.0.0

### What happened?

Expected the text to wrap according to `lv_obj_set_style_max_width` constraint

bug

### How to reproduce?

```c
lv_obj_t* text_new(lv_obj_t* parent, const char* txt)
{
    lv_obj_t* text = lv_label_create(parent);
    lv_label_set_text_static(text, txt);
    lv_obj_set_style_text_color(text, lv_color_white(), 0);
    lv_obj_set_style_bg_color(text, lv_color_black(), 0);
    lv_obj_set_style_pad_all(text, 10, 0);
    lv_obj_set_style_bg_opa(text, LV_OPA_COVER, 0);
    lv_obj_set_style_text_align(text, LV_TEXT_ALIGN_CENTER, 0);

    return text;
}

void text_doesnt_wrap_on_max_width(lv_obj_t* parent)
{
    lv_obj_t* root = lv_obj_create(lv_screen_active());
    lv_obj_set_size(root, lv_pct(100), lv_pct(100));
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(root, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_gap(root, 10, 0);

    // short text
    lv_obj_t* one = text_new(root, "1111");

    // set manual width
    lv_obj_t* two = text_new(root, "2222222222222222");
    lv_obj_set_width(two, 100);

    // expected text to be wrapped, similar to `two` / `four (workaround)`
    lv_obj_t* three = text_new(root, "3333333333333333");
    lv_obj_set_style_max_width(three, 100, 0);

    // hacky workaround: manual wrapping
    lv_obj_t* four = text_new(root, "4444444444444444");
    int32_t pad = lv_obj_get_style_pad_left(four, 0);
    if (lv_obj_get_self_width(four) + 2 * pad > 100) {
        lv_obj_set_width(four, 100);
        lv_obj_update_layout(four);
        lv_obj_set_width(four, lv_obj_get_self_width(four) + pad);
    }
}
```

### PR DESCRIPTION
**Pull request by kisvegabor**
### Description of the feature or fix

fixes #5636, #3420

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by C47D — APPROVED** [review]
Thanks for the fix.

File: tests/src/test_cases/widgets/test_label.c [hunk 1]
```diff
@@ -592,4 +589,24 @@ void test_label_rtl_dot_long_mode(void)
...
+
+    lv_obj_t * test_label2 = lv_label_create(lv_screen_active());
+    lv_label_set_text(test_label2, long_text);
+    lv_obj_set_width(test_label2, 600);
+    lv_obj_set_height(test_label2, 50);
+    lv_obj_set_x(test_label2, 300);
+    lv_obj_set_style_max_width(test_label2, 200, LV_PART_MAIN);
+    lv_label_set_long_mode(test_label2, LV_LABEL_LONG_DOT);
+
+    TEST_ASSERT_EQUAL_SCREENSHOT("widgets/label_max_width.png");
```
Comment (lhdjply) [inline tests/src/test_cases/widgets/test_label.c:609]: 1. Please upload the test picture.
2. This problem reflects that CI cannot indicate that the test picture is not uploaded.

Comment (kisvegabor) [reply tests/src/test_cases/widgets/test_label.c:609]: Thanks, added.

**Review by PGNetHun — APPROVED** [review]
