### PR TITLE
fix(wayland): use premultiplied alpha for transparent backgrounds #7543

### LINKED ISSUE #7543: [wayland] transparent background
### LVGL version

v9.2.2

### Platform

I'm using a customized [buildroot](https://github.com/buildroot/buildroot) ([2024.08.1](https://github.com/buildroot/buildroot/releases/tag/2024.08.1)) with a custom drm, wayland, weston, and a custom shell.

wayland: 1.23.0
wayland-protocols: 1.36
weston: 14.0.0

### What happened?

First, it seems that the Wayland driver in lvlg doesn't bring alpha support out of the box.
So I'm using this patch:
```patch
From 0dac73c87cae8c0358f0ccc8d332e3880ec00a05 Mon Sep 17 00:00:00 2001
From: Thomas Devoogdt <thomas.devoogdt@barco.com>
Date: Fri, 3 Jan 2025 15:26:33 +0100
Subject: [PATCH] wayland: add support for ARGB

Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>
---
 src/drivers/wayland/lv_wayland.c | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/src/drivers/wayland/lv_wayland.c b/src/drivers/wayland/lv_wayland.c
index dc71f6677..f6657f635 100644
--- a/src/drivers/wayland/lv_wayland.c
+++ b/src/drivers/wayland/lv_wayland.c
@@ -2535,6 +2535,8 @@ lv_display_t * lv_wayland_window_create(uint32_t hor_res, uint32_t ver_res, char
         return NULL;
     }
 
+    lv_display_set_color_format(window->lv_disp, LV_COLOR_FORMAT_ARGB8888);
+
     stride = lv_draw_buf_width_to_stride(hor_res,
                                          lv_display_get_color_format(window->lv_disp));
 
-- 
2.43.0

```
Not sure what the 'proper' way is? It would be nice to have some configuration parameter globally to indicate this support, or e.g. a boolean argument for `lv_wayland_window_create`.

The next issue arises when using rounding. Refer to the image below. The orange background belongs to another Wayland application positioned beneath the LVGL buttons. While the LVGL buttons occupy the entire screen, the remaining areas are transparent. Ideally, the rounded corners should display the same orange color as the background, but instead, they appear as a white square. Additionally, the white square is not entirely uniform—some orange is faintly visible within it. This could indicate an issue with incorrect premultiplied alpha handling.

image

### How to reproduce?

    lv_obj_set_style_bg_opa(
        lv_display_get_layer_bottom(display),
        LV_OPA_TRANSP, LV_PART_MAIN);

### PR DESCRIPTION
**Pull request by ThomasDevoogdt**
Fixes https://github.com/lvgl/lvgl/issues/7543.

See https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_shm.

wl_shm::format - pixel formats

For all wl_shm formats and unless specified in another protocol extension, pre-multiplied alpha is used for pixel values.

### CODE REVIEW

**Review by uLipe — DISMISSED** [review]

**Comment by kisvegabor** [comment]
Some confirmation of Wayland really sued premultiplied alpha: https://git.axiodl.com/encounter/SDL/commit/b528d48446c8c9c005ad122dddfdb2b46ad4553a

cc @etag4048

**Review by kisvegabor — DISMISSED** [review]

File: src/drivers/wayland/lv_wayland.c [hunk 1]
```diff
@@ -2221,6 +2224,11 @@ static void _lv_wayland_flush(lv_display_t * disp, const lv_area_t * area, unsig
     /* Modify specified area in buffer */
     for(y = area->y1; y <= area->y2; y++) {
         offset = ((area->x1 + (y * hres)) * bpp);
+        if(app->shm_format == WL_SHM_FORMAT_ARGB8888) {
+            for(x = area->x1; x <= area->x2; x++) {
+                lv_color_premultiply((lv_color32_t *)color_p + (x - area->x1));
+            }
```
Comment (kisvegabor) [inline src/drivers/wayland/lv_wayland.c]: Have less operations in the loop
```suggestion
            int32_t w = lv_area_get_width(area);
            for(x = 0; x < w; x++) {
                lv_color_premultiply((lv_color32_t *)color_p + x);
            }
```

Comment (ThomasDevoogdt) [reply src/drivers/wayland/lv_wayland.c]: I'm not sure if this will effectively compile in less operations. 

```
x = area->x1 // assign

x <= area->x2 // compare
(lv_color32_t *)color_p + (x - area->x1) // sum
```
vs

```
x = 0 // assign

x < w // compare
(lv_color32_t *)color_p + x // sum
```

The compiler is smart enough to combine `(lv_color32_t *)color_p - area->x1`, to end up in one operation.

The reason I wrote it like this, is simply to have some analogy/consistency with the vertical for loop.

Another option would have been to re-use the src_width/src_height variables. (Your lv_area_get_width in fact), but then I would have to change the vertical for loop to keep it consistent.

Comment (ThomasDevoogdt) [reply src/drivers/wayland/lv_wayland.c]: Update: I reworked the for loops slightly.

**Comment by ThomasDevoogdt** [comment]
@etag4048 @kisvegabor @etag4048 Is it possible to look further at this one?

**Review by uLipe — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
Looks good! One of our customers also confirmed that this change is required for correct blending! :tada:

**Comment by ThomasDevoogdt** [comment]
Thx @kisvegabor @uLipe for the review and merge.
