### PR TITLE
fix(layout): size in cross direction was not updated when layout on parent was changed from grid to flex

### LINKED ISSUE #8051: Flex container size in cross direction not updated correctly when switching layout
### LVGL version

master

### Platform

x11 simulator

### What happened?

When switching layout from grid to flex the childrens dimensions are not updated in cross direction.
https://github.com/user-attachments/assets/ec5f51f5-14c4-454f-93f1-65439a364339

### How to reproduce?

````
static void button_clicked_handler (lv_event_t *e)
{
  lv_obj_t *btn              = lv_event_get_target (e);
  lv_obj_t *layout_container = lv_event_get_user_data (e);

  int32_t layout = lv_obj_get_style_layout (layout_container, LV_PART_MAIN);
  if (layout == LV_LAYOUT_GRID)
  {
    lv_obj_set_layout (layout_container, LV_LAYOUT_FLEX);
    lv_obj_set_flex_flow (layout_container, LV_FLEX_FLOW_COLUMN);

    lv_obj_set_width (lv_obj_get_child (layout_container, 0), LV_PCT (100));
    lv_obj_set_width (lv_obj_get_child (layout_container, 1), LV_PCT (100));
    lv_obj_set_flex_grow (lv_obj_get_child (layout_container, 0), 1);
    lv_obj_set_flex_grow (lv_obj_get_child (layout_container, 1), 1);
    lv_obj_add_flag (lv_obj_get_child (layout_container, 2), LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag (lv_obj_get_child (layout_container, 3), LV_OBJ_FLAG_HIDDEN);
  }
  else
  {
    lv_obj_set_layout (layout_container, LV_LAYOUT_GRID);
    lv_obj_set_grid_dsc_array (layout_container, col_dsc, row_dsc);
    lv_obj_set_grid_align (layout_container, LV_GRID_ALIGN_SPACE_BETWEEN, LV_GRID_ALIGN_SPACE_BETWEEN);
    lv_obj_set_grid_cell (lv_obj_get_child (layout_container, 0), LV_GRID_ALIGN_STRETCH, 0, 1, LV_GRID_ALIGN_STRETCH, 0, 1);
    lv_obj_set_grid_cell (lv_obj_get_child (layout_container, 1), LV_GRID_ALIGN_STRETCH, 1, 1, LV_GRID_ALIGN_STRETCH, 0, 1);
    lv_obj_set_grid_cell (lv_obj_get_child (layout_container, 2), LV_GRID_ALIGN_STRETCH, 0, 1, LV_GRID_ALIGN_STRETCH, 1, 1);
    lv_obj_set_grid_cell (lv_obj_get_child (layout_container, 3), LV_GRID_ALIGN_STRETCH, 1, 1, LV_GRID_ALIGN_STRETCH, 1, 1);
    lv_obj_remove_flag (lv_obj_get_child (layout_container, 2), LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag (lv_obj_get_child (layout_container, 3), LV_OBJ_FLAG_HIDDEN);
  }
}

static void layout_change_init (void)
{
  lv_obj_t *screen = lv_display_get_screen_active (NULL);
  lv_obj_clean (screen);
  // Create a container object
  lv_obj_t *container = lv_obj_create (screen);
  lv_obj_set_size (container, lv_pct (100), lv_pct (80));
  lv_obj_set_style_pad_all (container, 10, 0);
  lv_obj_set_style_border_width (container, 0, 0);
  // lv_obj_set_style_bg_color (container, lv_color_white (), 0);
  lv_obj_align (container, LV_ALIGN_TOP_LEFT, 0, 0);

  // Set grid layout with 2 columns and 2 rows
  lv_obj_set_grid_dsc_array (container, col_dsc, row_dsc);
  lv_obj_set_layout (container, LV_LAYOUT_GRID);
  lv_obj_set_grid_align (container, LV_GRID_ALIGN_SPACE_BETWEEN, LV_GRID_ALIGN_SPACE_BETWEEN);

  // Create 4 objects with labels
  for (int i = 0; i < 4; i++)
  {
    lv_obj_t *obj = lv_obj_create (container);
    lv_obj_set_grid_cell (obj, LV_GRID_ALIGN_STRETCH, i % 2, 1, LV_GRID_ALIGN_STRETCH, i / 2, 1);

    lv_obj_t *label = lv_label_create (obj);
    lv_label_set_text_fmt (label, "Obj %d", i + 1);
    lv_obj_center (label);
  }

  // Create a button to toggle layout
  lv_obj_t *btn = lv_button_create (screen);
  lv_obj_align (btn, LV_ALIGN_BOTTOM_MID, 0, -15);
  lv_obj_t *btn_label = lv_label_create (btn);
  lv_label_set_text (btn_label, "Toggle Layout");

  // Event handler to toggle between grid and flex layout
  lv_obj_add_event_cb (btn, button_clicked_handler, LV_EVENT_CLICKED, container);
}
````

### PR DESCRIPTION
**Pull request by Pavi92**
Fixes #8051

When switching layout from grid to flex the childrens dimensions are not updated in cross direction.

### CODE REVIEW

**Review by PGNetHun — DISMISSED** [review]
Nice check :)

**Review by liamHowatt — COMMENTED** [review]
Thanks. Can I bother you to convert your example from the issue to a test case?

File: src/layouts/flex/lv_flex.c [hunk 1]
```diff
@@ -395,6 +395,10 @@ static void children_repos(lv_obj_t * cont, flex_t * f, int32_t item_first_id, i
             item = get_next_item(cont, f->rev, &item_first_id);
             continue;
         }
+
+        int16_t item_w_layout = item->w_layout;
+        int16_t item_h_layout = item->h_layout;
```
Comment (liamHowatt) [inline src/layouts/flex/lv_flex.c]: Oh, also, to match the struct member's type

```suggestion
        uint16_t item_w_layout = item->w_layout;
        uint16_t item_h_layout = item->h_layout;
```

File: tests/src/test_layout_switch.c [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+
+static lv_obj_t * active_screen = NULL;
+static lv_obj_t * objects[NUM_OBJECTS] = {NULL};
+static int32_t grid_col_dsc = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
+static int32_t grid_row_dsc = {LV_GRID_FR(1), LV_GRID_FR(1), LV_GRID_TEMPLATE_LAST};
+
+static void set_layout_grid(void)
+{
+    lv_obj_set_grid_dsc_array(active_screen, grid_col_dsc, grid_row_dsc);
+    lv_obj_set_grid_align(active_screen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_SPACE_BETWEEN);
```
Comment (liamHowatt) [inline tests/src/test_layout_switch.c]:
```suggestion
    lv_obj_set_grid_align(active_screen, LV_GRID_ALIGN_SPACE_BETWEEN, LV_GRID_ALIGN_SPACE_BETWEEN);
```

**Review by liamHowatt — COMMENTED** [review]
Thank you! Just one thing

**Review by liamHowatt — APPROVED** [review]

**Review by AndreCostaaa — APPROVED** [review]
CI issue is unrelated. Thank you :rocket:
