### PR TITLE
fix(cache): make the cache module private

### LINKED ISSUE #8690: Build problems due to including a private header (lv_cache_private.h) in the public headers
### LVGL version

v9.3.0

### Platform

Linux

### What happened?

The lv_cache_private.h header is included in the public header files:
```
lvgl.h
 - lv_cache.h
    - lv_cache_class.h
       - lv_cache_lru_rb.h
         - lv_cache_private.h
       - lv_cache_lru_ll.h
         - lv_cache_private.h
```

When installing the headers without the `CONFIG_LV_USE_PRIVATE_API` option enabled, this header file isn't installed because it matches the `*_private.h` [pattern](https://github.com/lvgl/lvgl/blob/master/env_support/cmake/os_desktop.cmake#L306) to exclude private headers. When trying to build **any** application using lvgl, compilation fails because the `lv_cache_private.h` header isn't found.

Possible solutions:

1. Rename the `lv_cache_private.h` header to something that doesn't match the pattern. For example  `lv_cache_priv.h` or `lv_cache_internal.h`. This way the file won't be excluded during installation.
2.  Add an extra cmake rule to install the header manually:
```
install(
    FILES "${LVGL_ROOT_DIR}/src/misc/cache/lv_cache_private.h"
    DESTINATION "${INC_INSTALL_DIR}/src/misc/cache")
```

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by AndreCostaaa**
Fixes #8690  

We're making this module private as it should've never been made public in the first place

The other solution would be to create a `create` or a `get` function for each cache class but we don't see the value of making this module public

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
cc @W-Mai

**Comment by jefdriesen** [comment]
I can confirm this PR fixes issue #8690.

**Comment by W-Mai** [comment]
Actually, we've used cache in our project, and when designing the cache module, we expected users to be able to freely use lvgl's cache system to accelerate their own resource or codes.

Maybe we could put it in lv_private.h in a more reasonable way.
What do you think?

**Comment by kisvegabor** [comment]
I agree to add it to `lvgl_private.h` as this way:
- it will make the generic API cleaner
- pro devs can still use it

**Comment by AndreCostaaa** [comment]
>Actually, we've used cache in our project, and when designing the cache module, we expected users to be able to freely use lvgl's cache system to accelerate their own resource or codes.

That's good to know. Keeping it public would mean a `get` or a `create` API for each class though which can come in the future if there's a real ask for it, for now I like the approach of keeping it private which means we can keep the current API

>Maybe we could put it in lv_private.h in a more reasonable way.
>What do you think?

Done!

Thank you for the feedback

**Comment by W-Mai** [comment]
Yes, in the future, when there are many cache classes, we can create a factory function to create different cache instances. Currently, there are not many classes, and the demand is not great.

File: tests/src/test_cases/draw/test_draw_svg.c [hunk 1]
```diff
@@ -1,5 +1,6 @@
 #if LV_BUILD_TEST
 #include "../lvgl.h"
+#include "../src/misc/cache/lv_cache.h"
```
Comment (W-Mai) [inline tests/src/test_cases/draw/test_draw_svg.c:3]: Is it better to use `lv_private.h` or directly include `lv_cache.h`?

Comment (AndreCostaaa) [reply tests/src/test_cases/draw/test_draw_svg.c:3]: I prefer only including what's actually used but there's no hard rule in LVGL afaik

Comment (W-Mai) [reply tests/src/test_cases/draw/test_draw_svg.c:3]: Get it

**Review by W-Mai — APPROVED** [review]

**Review by uLipe — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]
