### PR TITLE
fix(property): fix style property

### LINKED ISSUE #6551: lv_obj_set_property() function not work correctly when using style properties.
### LVGL version

v9.0.0

### What happened?

The macro #define LV_PROPERTY_ID(clz, name, type, index)    LV_PROPERTY_## clz ##_##name = (LV_PROPERTY_## clz ##_START + (index)) | ((type) << LV_PROPERTY_TYPE_SHIFT)
defines a property ID. But it does not store the real "index", it adds the property id start value to the index.
For example, the index of LV_STYLE_X is  8,  however the LV_PROPERTY_STYLE_X stores LV_STYLE_X + LV_PROPERTY_STYLE_START = 9. The problem will occur when set this property by using lv_obj_set_local_style_prop(), the second argument is the index of the style property.  
I think the code should be 
lv_obj_set_local_style_prop(obj, index - LV_PROPERTY_STYLE_START, value->style, value->selector);
instead of 
lv_obj_set_local_style_prop(obj, index, value->style, value->selector);

Anyone can help to check this ? 

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by XuNeo**
### Description of the feature or fix

The test case is out of date, `prop.id` should not use LV_STYLE_xxx enum directly. 
Set builtin last property ID to 0xffff, leaving 0x10000 to 0xfffffff for user.

Fix #6551

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by C47D — APPROVED** [review]

**Review by FASTSHIFT — DISMISSED** [review]

File: src/core/lv_obj_property.h [hunk 1]
```diff
@@ -56,15 +56,15 @@ enum {
     LV_PROPERTY_ID_INVALID      = 0,
 
     /*ID 0x01 to 0xff are style ID, check lv_style_prop_t*/
-    LV_PROPERTY_STYLE_START     = 0x01,
+    LV_PROPERTY_STYLE_START     = 0x00,
 
-    LV_PROPERTY_ID_START        = 0x100, /*ID little than 0xff is style ID*/
+    LV_PROPERTY_ID_START        = 0x0100, /*ID little than 0xff is style ID*/
```
Comment (kisvegabor) [inline src/core/lv_obj_property.h]:
```suggestion
    LV_PROPERTY_ID_START        = 0x0100, /*ID smaller than 0xff is style ID*/
```

**Review by kisvegabor — COMMENTED** [review]
Just a minor typo.

**Review by kisvegabor — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]
