### PR TITLE
fix(scale): fix angle calculation error

### LINKED ISSUE #7285: lv_scale -- Suggested Refactor
### Introduce the problem

cc:  @kisvegabor @C47D 

I would like to start with a compliment about `lv_scale_t`.  It's a nice model with its Sections and how nicely they dovetail with the drawing steps.

There are 3 issues with Scale that I have found:

1.  There are 2 field names in `_lv_scale_section_t` that are mis-named:

- `_lv_scale_section_t.minor_range` and
- `_lv_scale_section_t.major_range`

should really be called

- `_lv_scale_section_t.range_min` and
- `_lv_scale_section_t.range_max`

because their use is exclusively and only to compare against `_lv_scale_t.range_min` and `_lv_scale_t.range_max` respectively, and they have the *exact same semantics*.

Details:  More precisely stated, `Sections` make it possible for portions of a `Scale` to *convey meaning* by using different style properties to draw them (colors, line thicknesses, font, etc.).  A `Section` represents a sub-range of the `Scale`, whose styles (like cascading style sheets) take precedence while drawing the PARTS (lines, ticks and labels) of the `Scale` that are within the range of that `Section`.  *That is all these 2 values are used for is determining if the "scale value" of a PART being drawn (computed from `range_min` and `range_max`) is within the `min` and `max` value of the `Section`.*

To put it simply, `minor_range` and `major_range` are names that were chosen early by the original writer, and later, more appropriate names are found later, that more accurately reflect the meaning of their content.  (This is, of course, a common occurrence in software development, and is a classic case for refactoring by renaming fields of a custom data type.)

2.  The same structure uses 2 `uint32_t` values to store Boolean values.   They are:  `first_tick_idx_is_major` and `last_tick_idx_is_major`.  This is wasteful of RAM, and unless there is a future plan for them (not documented in the code), they could be reduced to single bits.  Thankfully these are also internal fields that will not break the API to change them.

3.  It is also worth considering that after a Section's creation using `lv_scale_add_section()`, it has a default range of [0..0], which *isn't neutral*.  I.e. a Tick at the 0-point on the Scale can be drawing using that Section's line-style properties.  So if, after creation, as Section is meant to be *neutral* (i.e. will not be drawn), a better approach would be to make the range [0..-1] so that that Section is guaranteed not to affect anything until a valid range has been assigned that at least overlaps part of the Scale's range, if it is not fully within it.

### Proposal

A.  Rename:

   - `_lv_scale_section_t.minor_range` => `range_min`, and
   - `_lv_scale_section_t.major_range` => `range_max`.

Thankfully, if `lv_scale_private.h` fulfills its role, this will not break the API.

Part of this refactoring also needs to include the formal argument names of the `lv_scale_section_set_range()` function (`minor_range` and `major_range`) to match those of `lv_scale_set_range()` (`min` and `max` for consistency) since their semantics are also identical.

B.  Change the type of `first_tick_idx_is_major` and `last_tick_idx_is_major` to single bits.

C.  If '3' above is a desirable trait, then setting
```
    section->major_range = -1;
```
at initialization time inside `lv_scale_add_section()` would be the change to implement it.  (As a note, these field are SIGNED, and they are currently being assigned UNSIGNED 0 values `0U` — doesn't make sense.)

### PR DESCRIPTION
**Pull request by vwheeler63**
This step started as an implementation of the refactor recommended in #7285.  In doing so, I also documented the fields of `struct _lv_scale_t` and `struct _lv_scale_section_t` since I was now intimately familiar with them.  In the process of updating the documentation in `lv_scale.h`, I discovered:

- There was an important bug in `lv_scale_set_rotation()` that caused part of the main scale line to be omitted in the drawing when negative values were passed, however drawing worked as intended for all values in range [0..360].  So instead of solving the drawing bug, I solved it by normalizing the angle in the range [0..360] before assigning the value to `scale->rotation`.

- While validating this normalization, I wrote a test and thought it would be appropriate to preserve that test in `test_scale.c`. So I did.  I don't know yet what calls these functions, so I have not hooked it up yet with whatever calls them.

- An important aspect of a scale's range (angular distance between low and high end of scale) was omitted from the documentation.  Handled in `scale.rst`.  (See [preview of updated portion of scale document here](http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/details/widgets/scale.html#setting-range).)

Resolves #7285

cc:  @kisvegabor 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.  Done.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.  n/a
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.  Done.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).  n/a
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).  Done.
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.  Done.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.  Done.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

File: src/widgets/scale/lv_scale.c [hunk 1]
```diff
@@ -389,6 +400,12 @@ int32_t lv_scale_get_major_tick_every(lv_obj_t * obj)
     return scale->major_tick_every;
 }
 
+lv_scale_mode_t lv_scale_get_rotation(lv_obj_t * obj)
+{
+    lv_scale_t * scale = (lv_scale_t *)obj;
```
Comment (uLipe) [inline src/widgets/scale/lv_scale.c:405]: Question, is it okay to perform a cast from lv_obj_t to lv_scale_t?

File: src/widgets/scale/lv_scale_private.h [hunk 2]
```diff
@@ -28,40 +28,49 @@ extern "C" {
...
+    uint32_t first_tick_idx_in_section;    /**< Internal (set during drawing): Tick index of first tick that falls within
+                                            *   this section; LV_SCALE_TICK_IDX_DEFAULT_ID if section contains no ticks. */
+    uint32_t last_tick_idx_in_section;     /**< Internal (set during drawing): Tick index of last tick that falls within
+                                            *   this section; LV_SCALE_TICK_IDX_DEFAULT_ID if section contains no ticks. */
+    int32_t first_tick_in_section_width;   /**< Internal (set during drawing) */
+    int32_t last_tick_in_section_width;    /**< Internal (set during drawing) */
+    lv_point_t first_tick_in_section;      /**< Internal (set during drawing) */
+    lv_point_t last_tick_in_section;       /**< Internal (set during drawing) */
+    uint32_t first_tick_idx_is_major : 1;  /**< Internal (set during drawing): true if
+                                            * `first_tick_idx_in_section` represents a major tick. */
```
Comment (uLipe) [inline src/widgets/scale/lv_scale_private.h:48]: The struct may reserve the whole uint32_t even if using 1 bit, is there any reason to limit the bit width? I'm afraid this is not portable across compilers

File: src/widgets/scale/lv_scale_private.h [hunk 3]
```diff
@@ -28,40 +28,49 @@ extern "C" {
...
+    lv_obj_t obj;                      /**< Base Widget part of Scale */
+    lv_ll_t section_ll;                /**< Linked list for the sections (stores lv_scale_section_t)*/
+    const char ** txt_src;             /**< Optional list of text strings for major ticks
+                                        *   when custom labels are provided. */
+    lv_scale_mode_t mode;              /**< Orientation and layout of scale. */
+    int32_t range_min;                 /**< Scale's minimum value */
+    int32_t range_max;                 /**< Scale's maximum value */
+    uint32_t total_tick_count   : 15;  /**< Total number of ticks (major and minor) */
+    uint32_t major_tick_every   : 15;  /**< Frequency of major ticks to minor ticks */
+    uint32_t label_enabled      : 1;   /**< Draw labels for major ticks? */
```
Comment (uLipe) [inline src/widgets/scale/lv_scale_private.h:63]: Same comment about the specific bit width

**Review by uLipe — COMMENTED** [review]
Just left a couple of questions

File: src/widgets/scale/lv_scale.c (hunk 1 above)
Comment (vwheeler63) [reply src/widgets/scale/lv_scale.c:405]: > Question, is it okay to perform a cast from lv_obj_t to lv_scale_t?

Yes, this is by design:  the two data types have the same field structure at the beginning.  `lv_obj_t` is the "[Base Widget](https://docs.lvgl.io/master/details/base-widget/index.html)" and all other widgets "inherit" from it.  The inheritance is implemented manually in C, but it is there.  That makes it okay to freely cast to and from `lv_obj_t`.  In a lot of places in the library there is a verification that the actual type passed is the correct Widget (i.e. sub-class of `lv_obj_t`) and it looks like `LV_ASSERT_OBJ(&widget, MY_CLASS)` and is active when `LV_USE_ASSERT_OBJ` macro is set to `1` in `lv_conf.h` -- which is a good idea during development and validation testing.  If you have an assertion-failure mechanism set up in your project, it catches when you pass, say, a Button Widget to a Scale function.

File: src/widgets/scale/lv_scale_private.h (hunk 2 above)
Comment (vwheeler63) [reply src/widgets/scale/lv_scale_private.h:48]: > The struct may reserve the whole uint32_t even if using 1 bit, is there any reason to limit the bit width? I'm afraid this is not portable across compilers

This is a good question.  I'd like to bring Gábor into this conversation.  I am mimicking what has been done in other similar structures.  @kisvegabor Thoughts?

Comment (vwheeler63) [reply src/widgets/scale/lv_scale_private.h:48]: @uLipe My first thoughts about compiler compatibility is that this `struct` is used only internally, so it is okay if padding between fields changes from compiler to compiler since the code that uses it will have been compiled by the same compiler.  But I would still like to get Gábor's insights.

Comment (kisvegabor) [reply src/widgets/scale/lv_scale_private.h:48]: We use bit fields on a lot of places and there was no complain about compiler issues so far.  

In this case there is no difference between 1 bit and `uint32_t` as the whole `uint32_t` will be used anyways. But if we added an other bit later, there wouldn't be extra memory usage.

Comment (uLipe) [reply src/widgets/scale/lv_scale_private.h:48]: It is more or less true actually, because even though  an extra bit or bits means no extra memory, if the layout of the struct changes the compiler (by architecture nature) will change the struct design in the memory to keep the architecture boundary alignment, which may lead to the inverse, extra memory consumption.

For the current usage,of bit-fields like this it is fair enough reason to use them,  from me I think this topic can be resolved, thanks @vwheeler63 and @kisvegabor

File: src/widgets/scale/lv_scale_private.h (hunk 3 above)
Comment (uLipe) [reply src/widgets/scale/lv_scale_private.h:63]: Same as above, feel free to resolve it

File: src/widgets/scale/lv_scale.c (hunk 1 above)
Comment (kisvegabor) [reply src/widgets/scale/lv_scale.c:405]: E.g. [Slider is a Bar](https://github.com/lvgl/lvgl/blob/master/src/widgets/slider/lv_slider_private.h#L31) and [Bar is an Obj](https://github.com/lvgl/lvgl/blob/master/src/widgets/bar/lv_bar_private.h#L38). So all the widgets can be treated as obj to add styles, set x, y, etc. (e.g. `lv_obj_set_x(slider1, 20)`);

File: src/widgets/scale/lv_scale.h [hunk 4]
```diff
@@ -85,120 +85,135 @@ lv_obj_t * lv_scale_create(lv_obj_t * parent);
...
 
 /**
- * Set properties specific to round scale
- * @param obj       pointer to a scale object
- * @param rotation  the angular offset from the 3 o'clock position (clock-wise)
+ * Set angular offset from the 3-o'clock position of the low end of the Scale.
+ * (Applies only to round Scales.)
+ * @param obj       pointer to Scale Widget
+ * @param rotation  clockwise angular offset (in degrees) from the 3-o'clock position
+ *                  of the low end of the scake; negative values are first normalized
```
Comment (kisvegabor) [inline src/widgets/scale/lv_scale.h]:
```suggestion
 *                  of the low end of the scale; negative and >360 values are first normalized
```

File: src/widgets/scale/lv_scale.h [hunk 5]
```diff
@@ -85,120 +85,135 @@ lv_obj_t * lv_scale_create(lv_obj_t * parent);
...
+ *                  Examples:
+ *                      -   0 = 3 o'clock (right side)
+ *                      -  30 = 4 o'clock
+ *                      -  60 = 5 o'clock
+ *                      -  90 = 6 o'clock
+ *                      - 135 = midway between 7 and 8 o'clock (default)
+ *                      - 180 = 9 o'clock
+ *                      - 270 = 12 o'clock
+ *                      - 300 = 1 o'clock
+ *                      - 330 = 2 o'clock
```
Comment (kisvegabor) [inline src/widgets/scale/lv_scale.h:147]:
```suggestion
 *                      - 330 = 2 o'clock
 *                      - -30 = 2 o'clock
 *                      - 390 = 4 o'clock
```

File: src/widgets/scale/lv_scale_private.h [hunk 6]
```diff
@@ -28,40 +28,49 @@ extern "C" {
...
+    uint32_t last_tick_idx_in_section;     /**< Internal (set during drawing): Tick index of last tick that falls within
+                                            *   this section; LV_SCALE_TICK_IDX_DEFAULT_ID if section contains no ticks. */
+    int32_t first_tick_in_section_width;   /**< Internal (set during drawing) */
+    int32_t last_tick_in_section_width;    /**< Internal (set during drawing) */
+    lv_point_t first_tick_in_section;      /**< Internal (set during drawing) */
+    lv_point_t last_tick_in_section;       /**< Internal (set during drawing) */
+    uint32_t first_tick_idx_is_major : 1;  /**< Internal (set during drawing): true if
+                                            * `first_tick_idx_in_section` represents a major tick. */
+    uint32_t last_tick_idx_is_major  : 1;  /**< Internal (set during drawing): true if
+                                            * `last_tick_idx_in_section` represents a major tick. */
```
Comment (kisvegabor) [inline src/widgets/scale/lv_scale_private.h:50]: We can create an a `draw_info_t` struct from these, create a local variable during drawing, and pass this local variable as a parameter to all scale draw functions. This way we would use less malloced memory for the widget and kept the the widget data cleaner too. 

E.g.
```c
lv_scale_draw_info_t draw_info = {};
...
scale_find_section_tick_idx(scale, &draw_info)
```

Comment (vwheeler63) [reply src/widgets/scale/lv_scale_private.h:50]: > We can create an a `draw_info_t`

I agree!  The fact that they are only keeping track of values that are both set and used only during drawing begs for that struct to be cleaned up in favor of temporary (local/stack) values instead.  Is it okay if that becomes a separate PR?

Comment (kisvegabor) [reply src/widgets/scale/lv_scale_private.h:50]: > Is it okay if that becomes a separate PR?

Absolutely!

File: src/widgets/scale/lv_scale.c (hunk 1 above)
Comment (uLipe) [reply src/widgets/scale/lv_scale.c:405]: Understood, so lv_obj_t is something like a base class that may have its properties extended to a particular widget. 

Feel free to resolve it.

File: src/widgets/scale/lv_scale_private.h (hunk 6 above)
Comment (vwheeler63) [reply src/widgets/scale/lv_scale_private.h:50]: > > Is it okay if that becomes a separate PR?
> 
> Absolutely!

It's funny:  I dreamed about doing this in my sleep last night....  I was seeing the code in my mind, plus how simple (and safe) it is to move those variables from the heap onto the stack....  😄 

I added it to my Trello tasks for LVGL so I don't forget it.  😉

**Review by kisvegabor — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]
