### PR TITLE
fix(draw_sw): fix letter outline multi-threading issues

### LINKED ISSUE #7864: Crashes in ThorVG related to Tiled rendering.
### LVGL version

v9.2.0-89-g0daebca18

### Platform

The vector drawing started crashing, on SDL in DIRECT mode when ``LV_OS_PTHREAD`` is used with multiple draw units 

### What happened?

This is what happens when ``lv_demo_vector_graphics_not_buffered()`` is called

@kisvegabor This started occuring right after #6761 got merged

```
=================================================================
==220093==ERROR: AddressSanitizer: SEGV on unknown address 0x60b000140000 (pc 0x5a14b1b26cf7 bp 0x718486997180 sp 0x718486997180 T2)
==220093==The signal is caused by a READ memory access.
    #0 0x5a14b1b26cf7 in UPSCALE /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgSwRle.cpp:268
    #1 0x5a14b1b283aa in _decomposeOutline /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgSwRle.cpp:734
    #2 0x5a14b1b28532 in _genRle /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgSwRle.cpp:758
    #3 0x5a14b1b28f59 in rleRender(SwRleData*, SwOutline const*, SwBBox const&, bool) /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgSwRle.cpp:992
    #4 0x5a14b1b2b1ca in shapeGenRle(SwShape*, tvg::RenderShape const*, bool) /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgSwShape.cpp:524
    #5 0x5a14b1b25c3f in SwShapeTask::run(unsigned int) /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgSwRenderer.cpp:156
    #6 0x5a14b1b2ea11 in tvg::TaskSchedulerImpl::request(tvg::Task*) /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgTaskScheduler.cpp:189
    #7 0x5a14b1b2e985 in tvg::TaskScheduler::request(tvg::Task*) /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgTaskScheduler.cpp:217
    #8 0x5a14b1b2506b in tvg::SwRenderer::prepareCommon(SwTask*, tvg::RenderTransform const*, tvg::Array<void*> const&, unsigned char, tvg::RenderUpdateFlag) /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgSwRenderer.cpp:765
    #9 0x5a14b1b2528e in tvg::SwRenderer::prepare(tvg::RenderShape const&, void*, tvg::RenderTransform const*, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgSwRenderer.cpp:809
    #10 0x5a14b1b0795f in tvg::Shape::Impl::update(tvg::RenderMethod*, tvg::RenderTransform const*, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) (/home/etag/lvgl/src/test/lv_port_linux_freetype/bin/lvglsim+0x2e995f)
    #11 0x5a14b1b0649d in tvg::Paint::Impl::update(tvg::RenderMethod*, tvg::RenderTransform const*, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgPaint.cpp:293
    #12 0x5a14b1b315c4 in tvg::Canvas::Impl::update(tvg::Paint*, bool) /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgCanvas.h:107
    #13 0x5a14b1b31486 in tvg::Canvas::Impl::push(std::unique_ptr<tvg::Paint, std::default_delete<tvg::Paint> >) /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgCanvas.h:77
    #14 0x5a14b1b31088 in tvg::Canvas::push(std::unique_ptr<tvg::Paint, std::default_delete<tvg::Paint> >) /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgCanvas.cpp:57
    #15 0x5a14b1ae2482 in tvg_canvas_push /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgCapi.cpp:93
    #16 0x5a14b19aac6d in _task_draw_cb /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/draw/sw/lv_draw_sw_vector.c:402
    #17 0x5a14b1a69ec0 in lv_vector_for_each_destroy_tasks /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/draw/lv_draw_vector.c:791
    #18 0x5a14b19ab216 in lv_draw_sw_vector /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/draw/sw/lv_draw_sw_vector.c:440
    #19 0x5a14b19764b2 in execute_drawing /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/draw/sw/lv_draw_sw.c:537
    #20 0x5a14b1975985 in execute_drawing_unit /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/draw/sw/lv_draw_sw.c:383
    #21 0x5a14b19760af in render_thread_cb /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/draw/sw/lv_draw_sw.c:490
    #22 0x5a14b1877e9b in generic_callback /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/osal/lv_pthread.c:174
    #23 0x718487294ac2 in start_thread nptl/pthread_create.c:442
    #24 0x71848732684f  (/lib/x86_64-linux-gnu/libc.so.6+0x12684f)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/libs/thorvg/tvgSwRle.cpp:268 in UPSCALE
Thread T2 created by T0 here:
    #0 0x718488458685 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x5a14b1877878 in lv_thread_init /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/osal/lv_pthread.c:50
    #2 0x5a14b1974b84 in lv_draw_sw_init /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/draw/sw/lv_draw_sw.c:180
    #3 0x5a14b1861ce1 in lv_init /home/etag/lvgl/src/test/lv_port_linux_freetype/lvgl/src/lv_init.c:197
    #4 0x5a14b185fbcf in main /home/etag/lvgl/src/test/lv_port_linux_freetype/main.c:163
    #5 0x718487229d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

==220093==ABORTING
```

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by kisvegabor**
cc @etag4048 @liamHowatt 

fixes #7864

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

File: src/draw/sw/lv_draw_sw_letter.c [hunk 1]
```diff
@@ -313,13 +328,12 @@ static void draw_letter_outline(lv_draw_task_t * t, lv_draw_glyph_dsc_t * glyph_
     img_dsc.src = draw_buf;
     lv_draw_sw_image(t, &img_dsc, &letter_coords);
 
-    lv_vector_dsc_delete(vector_dsc);
```
Comment (liamHowatt) [inline src/draw/sw/lv_draw_sw_letter.c]: This variable still has some allocated memory associated with it because it still comes from `lv_vector_dsc_create`.

**Review by liamHowatt — COMMENTED** [review]
Is this ok still, or does it need to be updated?

https://github.com/lvgl/lvgl/blob/ebb73766481faa9e635c1e8ec259e2b1ea9c515f/src/draw/sw/lv_draw_sw.c#L98-L105

File: src/draw/sw/lv_draw_sw_letter.c (hunk 1 above)
Comment (kisvegabor) [reply src/draw/sw/lv_draw_sw_letter.c]: I see what's going now. Vector data is freed on multiple places in chunks. I needed to add a slight rework to make it work in correctly.

File: src/draw/lv_draw_vector.c [hunk 2]
```diff
@@ -790,6 +790,8 @@ void lv_vector_dsc_skew(lv_vector_dsc_t * dsc, float skew_x, float skew_y)
 
 void lv_vector_for_each_destroy_tasks(lv_ll_t * task_list, vector_draw_task_cb cb, void * data)
 {
+    if(task_list == NULL) return;
```
Comment (uLipe) [inline src/draw/lv_draw_vector.c:793]: task_list being NULL is something okay to happen, or this is just a protection against a catastrophic failure? In later case, I suggest to always put a LOG_WRN for better debugging experience

**Review by uLipe — COMMENTED** [review]
Just my first pass.

File: src/draw/lv_draw_vector.c (hunk 2 above)
Comment (kisvegabor) [reply src/draw/lv_draw_vector.c:793]: It's a workaround for a not perfectly clear life cycle management. Various parts of the vector descriptors are freed at various stages, so it can heppen that the things here are already freed. 

We should have a larger refactor here in the future.

**Comment by liamHowatt** [comment]
Do you have any comment on this question in my review?

> Is this ok still, or does it need to be updated?

File: src/draw/lv_draw_vector.c (hunk 2 above)
Comment (uLipe) [reply src/draw/lv_draw_vector.c:793]: I see it, even though it still something to handle, it is part of larger problem not being handled here, I'm okay to resolve it for now.

**Review by liamHowatt — APPROVED** [review]
After discussing, we agreed to keep the `tvg` init as-is.

**Review by uLipe — APPROVED** [review]
