### PR TITLE
fix(matrix): use homogeneous coordinates to transform point

### LINKED ISSUE #7959: matrix vertex transformation does not support homogeneous coordinates
### LVGL version

V9.3.0

### Platform

ARM  Cortex-M33

### What happened?

When I enabled the matrix transformation feature `LV_DRAW_TRANSFORM_USE_MATRIX` and performed image transformations on my development platform, I found that my image was not being fully rendered on the screen. 
Since I used a tiled rendering scheme, the issue was that some of the tiles at the end of the image did not generate proper rendering tasks to be sent to the rendering units.

Tracing back through the drawing steps, I discovered that during the matrix transformation calculations of the four sets of vertices of the image,`lv_matrix_transform_precise_point`, the third row of the matrix, which involves homogeneous coordinates, was not included in the transformation. 

 This differed from how my GPU handles transformations. After modifying the matrix transformation API, my image was rendered correctly.

I will open a pull request to fix this.

### How to reproduce?

Reproduction code
  ```
    lv_obj_t *img2 = lv_image_create(lv_screen_active());
    LV_IMG_DECLARE(w3w);
    lv_image_set_src(img2, &w3w);
    lv_obj_add_flag(img2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
    lv_matrix_t m =
    {
        .m = {
            0.556014f, 0.000000f, -133.384476f,   // m00, m01, m02
            -0.237900f, 0.735305f, 47.298244f,    // m10, m11, m12
            -0.000948f, 0.000000f, 0.922279f      // m20, m21, m22
        }
    };
    lv_obj_set_transform(img2, &m);
```

### PR DESCRIPTION
**Pull request by hellsge**
Fixes #7959

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
@FASTSHIFT please take a look at it

File: src/misc/lv_matrix.c [hunk 1]
```diff
@@ -180,8 +180,9 @@ bool lv_matrix_inverse(lv_matrix_t * matrix, const lv_matrix_t * m)
 lv_point_precise_t lv_matrix_transform_precise_point(const lv_matrix_t * matrix, const lv_point_precise_t * point)
 {
     lv_point_precise_t p;
-    p.x = (lv_value_precise_t)roundf(point->x * matrix->m[0][0] + point->y * matrix->m[0][1] + matrix->m[0][2]);
-    p.y = (lv_value_precise_t)roundf(point->x * matrix->m[1][0] + point->y * matrix->m[1][1] + matrix->m[1][2]);
+    lv_value_precise_t w = point->x * matrix->m[2][0] + point->y * matrix->m[2][1] + matrix->m[2][2];
+    p.x = (lv_value_precise_t)roundf((point->x * matrix->m[0][0] + point->y * matrix->m[0][1] + matrix->m[0][2]) / w);
+    p.y = (lv_value_precise_t)roundf((point->x * matrix->m[1][0] + point->y * matrix->m[1][1] + matrix->m[1][2]) / w);
```
[the remark this answers is not in the document]
Comment (kisvegabor) [reply src/misc/lv_matrix.c]: Sorry for the delay. Just tried the copilot reviewer and it seems working :slightly_smiling_face:

[the remark this answers is not in the document]
Comment (hellsge) [reply src/misc/lv_matrix.c:185]: > Sorry for the delay. Just tried the copilot reviewer and it seems working 🙂

Since each matrix has undergone normalization and the standard matrix operation process, w here will not be zero. If the user directly inputs an illegal matrix, there is a possibility of having a zero value here. This is useful.

[the remark this answers is not in the document]
Comment (hellsge) [reply src/misc/lv_matrix.c]: In fact, if `w` is 0, then the matrix being passed in must be invalid, and this invalid matrix must have been generated by the user. 
Therefore, I accepted the changes made by Copilot.

File: src/misc/lv_matrix.c [hunk 2]
```diff
@@ -180,8 +180,14 @@ bool lv_matrix_inverse(lv_matrix_t * matrix, const lv_matrix_t * m)
 lv_point_precise_t lv_matrix_transform_precise_point(const lv_matrix_t * matrix, const lv_point_precise_t * point)
 {
     lv_point_precise_t p;
-    p.x = (lv_value_precise_t)roundf(point->x * matrix->m[0][0] + point->y * matrix->m[0][1] + matrix->m[0][2]);
-    p.y = (lv_value_precise_t)roundf(point->x * matrix->m[1][0] + point->y * matrix->m[1][1] + matrix->m[1][2]);
+    lv_value_precise_t w = point->x * matrix->m[2][0] + point->y * matrix->m[2][1] + matrix->m[2][2];
+    if (w == 0) {
```
Comment (FASTSHIFT) [inline src/misc/lv_matrix.c]: Floating point numbers cannot be simply compared to 0. This should be modified to: `LV_ABS(w) < FLT_EPSILON`.

**Comment by W-Mai** [comment]
I wonder if I need to open a new function to deal with normalization, because it would add more operations and most of the time this calculation is not used.

**Comment by FASTSHIFT** [comment]
Please fix the code format: https://github.com/lvgl/lvgl/actions/runs/14299094241/job/40070412186?pr=7960

Run scripts/code-format.py (astyle v3.4.12 needs to installed by running cd scripts; ./install_astyle.sh) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).

**Comment by FASTSHIFT** [comment]
> I wonder if I need to open a new function to deal with normalization, because it would add more operations and most of the time this calculation is not used.

Yes, when the renderer does not support perspective, this calculation can be ignored. We can add configuration items to control the calculation behavior.

**Comment by hellsge** [comment]
> > I wonder if I need to open a new function to deal with normalization, because it would add more operations and most of the time this calculation is not used.
> 
> Yes, when the renderer does not support perspective, this calculation can be ignored. We can add configuration items to control the calculation behavior.

The current discussion about matrix operations on points requires enabling `LV_DRAW_TRANSFORM_USE_MATRIX`. This means that the user actively requests to use matrix transformations, so performing complete matrix operations and taking on additional floating-point calculations seems reasonable.

File: src/misc/lv_matrix.c (hunk 2 above)
Comment (hellsge) [reply src/misc/lv_matrix.c]: It has been fixed, please check.

File: src/misc/lv_matrix.c [hunk 3]
```diff
@@ -180,8 +181,15 @@ bool lv_matrix_inverse(lv_matrix_t * matrix, const lv_matrix_t * m)
...
-    p.y = (lv_value_precise_t)roundf(point->x * matrix->m[1][0] + point->y * matrix->m[1][1] + matrix->m[1][2]);
+    lv_value_precise_t w = point->x * matrix->m[2][0] + point->y * matrix->m[2][1] + matrix->m[2][2];
+    if(LV_ABS(w) < FLT_EPSILON) {
+        p.x = 0;
+        p.y = 0;
+    }
+    else {
+        p.x = (lv_value_precise_t)roundf((point->x * matrix->m[0][0] + point->y * matrix->m[0][1] + matrix->m[0][2]) / w);
+        p.y = (lv_value_precise_t)roundf((point->x * matrix->m[1][0] + point->y * matrix->m[1][1] + matrix->m[1][2]) / w);
+    }
```
Comment (uLipe) [inline src/misc/lv_matrix.c:195]: is not possible to replace the division with reciprocal multiplication to speed up the things here?

File: src/misc/lv_matrix.c [hunk 4]
```diff
@@ -180,8 +181,15 @@ bool lv_matrix_inverse(lv_matrix_t * matrix, const lv_matrix_t * m)
...
     lv_point_precise_t p;
-    p.x = (lv_value_precise_t)roundf(point->x * matrix->m[0][0] + point->y * matrix->m[0][1] + matrix->m[0][2]);
-    p.y = (lv_value_precise_t)roundf(point->x * matrix->m[1][0] + point->y * matrix->m[1][1] + matrix->m[1][2]);
+    lv_value_precise_t w = point->x * matrix->m[2][0] + point->y * matrix->m[2][1] + matrix->m[2][2];
+    if(LV_ABS(w) < FLT_EPSILON) {
+        p.x = 0;
+        p.y = 0;
+    }
+    else {
+        p.x = (lv_value_precise_t)roundf((point->x * matrix->m[0][0] + point->y * matrix->m[0][1] + matrix->m[0][2]) / w);
```
Comment (uLipe) [inline src/misc/lv_matrix.c]: Since we have a division here, I think we should also test for NaN cases and raise at least a LOG_ERR .

**Review by uLipe — COMMENTED** [review]
Nice work, I just have two questions.

File: src/misc/lv_matrix.c (hunk 4 above)
Comment (hellsge) [reply src/misc/lv_matrix.c]: First way, user use matrix tranform API like `lv_matrix_translate` `lv_matrix_scale` `lv_matrix_rotate` `lv_matrix_skew`, since there is no perspective transformation, m[0][2] m[1][2] m[2][2] will be  0,0,1.
Another way, user use `lv_obj_set_transform` to set a perspective matrix, then w may not be 1 but should not be 0.
 Therefore, if w is 0, it is an illegal matrix, it seems we should add a LOG_ERR here.

File: src/misc/lv_matrix.c (hunk 3 above)
Comment (hellsge) [reply src/misc/lv_matrix.c:195]: done, please check

File: src/misc/lv_matrix.c (hunk 4 above)
Comment (hellsge) [reply src/misc/lv_matrix.c]: done, please check

**Review by liamHowatt — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]
