### PR TITLE
fix(tabview): emit LV_EVENT_VALUE_CHANGED on header-button taps

### LINKED ISSUE #8536: LV_EVENT_VALUE_CHANGED not emitted when switching tabs via button click (works via swipe)
### LVGL version

v9.3.0

### Platform

| Item             | Value                         |
|------------------|-------------------------------|
| **LVGL version** | 9.3.0 |
| **Board / MCU**  | ESP32-S3 (WT32-SC01-Plus)     |
| **Display**      | ILI9341 via SPI              |
| **Touch**        | FT6336                        |

### Steps to reproduce

1. Create a `lv_tabview` with ≥2 tabs (see **Minimal code** below).  
2. Attach an `LV_EVENT_VALUE_CHANGED` listener to the tabview.  
3. **Swipe** to another tab → event *fires* ✅  
4. **Click** the tab-bar button → event **does not fire** ❌  

---

### Expected behaviour

`LV_EVENT_VALUE_CHANGED` should be sent **whenever the active tab changes**, no matter whether the change came from

* swipe/scroll (`cont_scroll_end_event_cb`), **or**
* button click (`button_clicked_event_cb`).

---

### Actual behaviour

| Action | Event emitted? |
|--------|----------------|
| Swipe  | ✅ Yes |
| Click  | ❌ No  |

---

### Minimal code (self-contained)

```c
static void tab_changed_cb(lv_event_t * e)
{
    uint32_t idx = lv_tabview_get_tab_active(lv_event_get_target(e));
    LV_LOG_USER("Tab changed → %u", idx);
}

void ui_init(void)
{
    lv_obj_t * scr = lv_scr_act();
    lv_obj_t * tv  = lv_tabview_create(scr);

    lv_tabview_add_tab(tv, "Tab 1");
    lv_tabview_add_tab(tv, "Tab 2");

    lv_obj_add_event_cb(tv, tab_changed_cb, LV_EVENT_VALUE_CHANGED, NULL);
}

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by bmts**
Header-button clicks did not raise LV_EVENT_VALUE_CHANGED, so application-level callbacks saw swipes but not direct taps. `button_clicked_event_cb()` now stores the previous tab index and, after calling `lv_tabview_set_active()`, sends LV_EVENT_VALUE_CHANGED when the tab really changes.  This makes header taps and swipe gestures behave consistently.

Fixes #8536

### CODE REVIEW

**Review by vwheeler63 — APPROVED** [review]
I concur this was needed, as this functionality should be consistent regardless of how the tab index is changed.  Thank you very much for submitting this PR!

File: src/widgets/tabview/lv_tabview.c [hunk 1]
```diff
@@ -305,8 +305,23 @@ static void button_clicked_event_cb(lv_event_t * e)
...
+
+    if(tv == NULL) return;
+
+    /* Remember currently active tab before the click */
+    uint32_t prev_idx = lv_tabview_get_tab_active(tv);
+
+    /* Index of the button that was clicked */
+    uint32_t idx = lv_obj_get_index_by_type(button, &lv_button_class);
+
+    /* Switch to the requested tab (no animation, like original code) */
```
Comment (AndreCostaaa) [inline src/widgets/tabview/lv_tabview.c]:
```suggestion
    /* Switch to the requested tab */
```

**Review by AndreCostaaa — APPROVED** [review]
Thank you ! :rocket: 

Fixes #8420

**Comment by bmts** [comment]
Build fixed!

**Review by uLipe — APPROVED** [review]
