### PR TITLE
fix(nema): Broken build after draw unit refactoring, draw_label changes

### LINKED ISSUE #7439: lv_demo_ebike() glitches
### LVGL version

9.3.0.dev

### Platform

STM32U5G9, GCC 13 compiler on Windows, NEMA GFX enabled

### What happened?

IMG_0512

### How to reproduce?

_No response_

### LINKED ISSUE #7691: Broken build on lv_draw_nema_gfx.c after 'refactor(draw): use task instead of draw_unit'
### LVGL version

tip of master

### Platform

The members `.target_layer` and `.clip_area`  of `base_unit` are moved to another structure.

lvgl\src\draw\nema_gfx\lv_draw_nema_gfx.c [265]:
`    t->state = LV_DRAW_TASK_STATE_IN_PROGRESS;
    draw_nema_gfx_unit->base_unit.target_layer = layer;
    draw_nema_gfx_unit->base_unit.clip_area = &t->clip_area;
    draw_nema_gfx_unit->task_act = t;
`

### What happened?

Build error

### How to reproduce?

_No response_

### LINKED ISSUE #7723: Nema GFX large fonts not rendered correctly
### LVGL version

master

### Platform

STM32U5G9

### Config

``` 
#define LV_COLOR_DEPTH 16
#define LV_USE_OS   LV_OS_FREERTOS
#define LV_USE_NEMA_GFX 1
#define LV_USE_NEMA_VG 1
```

### What happened?

Image

#### How to reproduce?

``` 
#define APP_UI_FONT(size) &Roboto_Regular_##size
static lv_font_t *fonts[] = {
    APP_UI_FONT (8), 
    APP_UI_FONT (12), 
    APP_UI_FONT (16), 
    APP_UI_FONT (24),
    APP_UI_FONT (32),
    APP_UI_FONT (40),
    APP_UI_FONT (48), 
    APP_UI_FONT (80),
  };

  uint32_t size = ARRAY_SIZE (fonts);

  lv_obj_t *screen = lv_screen_active ();
  lv_obj_set_style_bg_color (screen, lv_color_white (), 0);

  lv_obj_set_layout (screen, LV_LAYOUT_FLEX);
  lv_obj_set_flex_flow (screen, LV_FLEX_FLOW_COLUMN);

  for (size_t i = 0; i < size; i++)
  {
    lv_obj_t *label = lv_label_create (screen);
    lv_obj_set_flex_align (label, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_text_font (label, fonts[i], 0);
    lv_obj_set_style_text_color (label, lv_color_black (), 0);
    lv_label_set_text (label, "ADIVST0I");
  }
```

### PR DESCRIPTION
**Pull request by MarkIoanAmat**
Fixes #7691
Fixes #7723
Fixes #7439

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by uLipe — DISMISSED** [review]

**Comment by MarkIoanAmat** [comment]
@liamHowatt @uLipe @kisvegabor 
I also added some new color formats and the fix for a glitching bug found in e-bike (cant find the ticket though) I think it was initially reported by @tdjastrzebski

Also fixes #7723

File: src/draw/nema_gfx/lv_draw_nema_gfx_label.c [hunk 1]
```diff
@@ -793,12 +818,15 @@ static void _draw_letter(lv_draw_task_t * t, lv_draw_glyph_dsc_t * dsc,  const l
         }
 
         /* Performance Optimization for lv_font_fmt_txt_dsc_t fonts, always request raw bitmaps */
-        g.req_raw_bitmap = 1;
+        /*Exception for w*h >= 2046*/
```
Comment (uLipe) [inline src/draw/nema_gfx/lv_draw_nema_gfx_label.c]: Nit: I think the comment could explain why 2046 case means

File: src/draw/nema_gfx/lv_draw_nema_gfx_label.c [hunk 2]
```diff
@@ -793,12 +818,15 @@ static void _draw_letter(lv_draw_task_t * t, lv_draw_glyph_dsc_t * dsc,  const l
...
         is_raw_bitmap = false;
-        if(font->get_glyph_bitmap == lv_font_get_bitmap_fmt_txt) {
-            lv_font_fmt_txt_dsc_t * fdsc = (lv_font_fmt_txt_dsc_t *)font->dsc;
-            if(fdsc->bitmap_format == LV_FONT_FMT_TXT_PLAIN) {
-                is_raw_bitmap = true;
+        if(g.box_h * g.box_w <= 2046) {
```
Comment (uLipe) [inline src/draw/nema_gfx/lv_draw_nema_gfx_label.c]: Also here, if its a magic number, define it with a meaninguful name :)

**Review by uLipe — CHANGES_REQUESTED** [review]
Great work I have just two small nits :)

File: src/draw/nema_gfx/TSILVGL.code-workspace [hunk 3]
```diff
@@ -0,0 +1,11 @@
+{
```
Comment (kisvegabor) [inline src/draw/nema_gfx/TSILVGL.code-workspace]: This file should be removed.

File: src/draw/nema_gfx/lv_draw_nema_gfx_label.c (hunk 2 above)
Comment (MarkIoanAmat) [reply src/draw/nema_gfx/lv_draw_nema_gfx_label.c]: It is a magic number indeed :) I will add a define instead. It refers to a limitation on HW regarding a special data handling case.

**Comment by MarkIoanAmat** [comment]
Also found ticket for e-bike glitch, was #7439

**Review by kisvegabor — DISMISSED** [review]

**Comment by kisvegabor** [comment]
Thank you! @uLipe when you will have some spare time, please check Dave2D and update it if needed.

**Comment by kisvegabor** [comment]
> Also found ticket for e-bike glitch, was https://github.com/lvgl/lvgl/issues/7439

Will you send a PR for this?

**Comment by MarkIoanAmat** [comment]
@kisvegabor It is fixed in this PR

**Comment by kisvegabor** [comment]
Great! @liamHowatt is on a holiday today, but he can test it tomorrow.

**Comment by MarkIoanAmat** [comment]
@uLipe @liamHowatt Can we procced with this PR ?

File: src/draw/nema_gfx/lv_draw_nema_gfx.c [hunk 4]
```diff
@@ -91,16 +93,17 @@ static int32_t nema_gfx_delete(lv_draw_unit_t * draw_unit);
 void lv_draw_nema_gfx_init(void)
 {
     lv_draw_nema_gfx_unit_t * draw_nema_gfx_unit = lv_draw_create_unit(sizeof(lv_draw_nema_gfx_unit_t));
-    /*Initialize NemaGFX*/
+    /*Initiallize NemaGFX*/
```
Comment (liamHowatt) [inline src/draw/nema_gfx/lv_draw_nema_gfx.c]: Was correct before (and other)

File: src/draw/nema_gfx/lv_draw_nema_gfx_label.c [hunk 5]
```diff
@@ -320,35 +324,54 @@ static void _draw_nema_gfx_letter(lv_draw_task_t * t, lv_draw_glyph_dsc_t * glyp
...
                 };
-
                 nema_set_matrix(m);
                 nema_raster_rect(x, y, w, h);
             }
             else {
-                nema_bind_src_tex((uintptr_t)(mask_buf), w, h, _bpp_nema_gfx_format(glyph_draw_dsc), -1,
-                                  NEMA_FILTER_PS);
-                nema_blit(x, y);
+                nema_bind_src_tex((uintptr_t)(mask_buf), lv_area_get_width(&mask_area), lv_area_get_height(&mask_area), src_cf,
```
Comment (liamHowatt) [inline src/draw/nema_gfx/lv_draw_nema_gfx_label.c:368]: Can it happen that `mask_buf` is used uninitialized if `is_raw_bitmap && glyph_draw_dsc->format > LV_FONT_GLYPH_FORMAT_A4`?

File: src/draw/nema_gfx/lv_draw_nema_gfx_label.c [hunk 6]
```diff
@@ -320,35 +324,54 @@ static void _draw_nema_gfx_letter(lv_draw_task_t * t, lv_draw_glyph_dsc_t * glyp
...
+                                  lv_area_get_width(&mask_area),
+                                  NEMA_FILTER_BL);
+                nema_blit_rect(x, y, w, h);
+                lv_draw_nema_gfx_unit_t * draw_nema_gfx_unit = (lv_draw_nema_gfx_unit_t *)t->draw_unit;
+                nema_cl_submit(&(draw_nema_gfx_unit->cl));
+                nema_cl_wait(&(draw_nema_gfx_unit->cl));
```
Comment (liamHowatt) [inline src/draw/nema_gfx/lv_draw_nema_gfx_label.c:374]: Is the wait needed? You added a new `wait_for_finish_cb`

File: src/draw/nema_gfx/lv_draw_nema_gfx_label.c [hunk 7]
```diff
@@ -320,35 +324,54 @@ static void _draw_nema_gfx_letter(lv_draw_task_t * t, lv_draw_glyph_dsc_t * glyp
...
+            lv_area_t mask_area = *glyph_draw_dsc->letter_coords;
+
+            lv_area_t rel_coords;
+            lv_area_copy(&rel_coords, &blend_area);
+            lv_area_move(&rel_coords, -layer->buf_area.x1, -layer->buf_area.y1);
 
+            int32_t x, y, w, h;
+
+            /*Read the static font*/
             if(is_raw_bitmap) {
```
Comment (MarkIoanAmat) [inline src/draw/nema_gfx/lv_draw_nema_gfx_label.c:337]: @liamHowatt mask_buf will be always initialized either from glyph_data or draw_buf->data

File: src/draw/nema_gfx/lv_draw_nema_gfx_label.c (hunk 6 above)
Comment (MarkIoanAmat) [reply src/draw/nema_gfx/lv_draw_nema_gfx_label.c:374]: Yes it is needed, we have to ensure that glyph is drawn before deleting any buffer. That why it is not needed when we have to draw the static font (raw_bitmap) as it is already and always in the memory. The wait_for_finish_cb will be used differently. I just added it now for the TSC compression part.

File: src/draw/nema_gfx/lv_draw_nema_gfx.c (hunk 4 above)
Comment (MarkIoanAmat) [reply src/draw/nema_gfx/lv_draw_nema_gfx.c]: Missed that thank you for noticing it.

**Review by uLipe — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
