### PR TITLE
fix(obj): fix crash with LV_SIZE_CONTENT parent and % positioned child

### LINKED ISSUE #6837: Parent `height` set to `LV_SIZE_CONTENT` and child `y` position set using `LV_PCT` macro
### LVGL version

v9.1 v8.4

### What happened?

When there is a parent widget which `height` is set to `LV_SIZE_CONTENT` and a child widget which `y` position is set using `LV_PCT` macro then actual `y` position in px of the child will not be calculated correctly - it looks to me that height of the parent used in this calculation is not actual height calculated from the content but something else. And for some values given to the LV_PCT macro the LVGL code will freeze, looping forever.

### How to reproduce?

This code will make LVGL to freeze:

```
    // parent obj
    lv_obj_t *parent_obj = lv_img_create(lv_scr_act());
    lv_obj_set_pos(parent_obj, 0, 0);
    lv_obj_set_size(parent_obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);               // parent height set to LV_SIZE_CONTENT
    lv_img_set_src(parent_obj, &img_img_astra_top_view);
    lv_image_set_inner_align(parent_obj, LV_IMAGE_ALIGN_DEFAULT);

        // child object
        lv_obj_t *child_obj = lv_img_create(parent_obj );
        lv_obj_set_pos(child_obj , 0, LV_PCT(100));                    // child y position set to LV_PCT(100)
        lv_obj_set_size(child_obj , LV_SIZE_CONTENT, LV_SIZE_CONTENT);
        lv_img_set_src(child_obj , &img_img_brake_lights_on);
        lv_image_set_inner_align(child_obj , LV_IMAGE_ALIGN_DEFAULT);
```

Both images, `img_img_astra_top_view` and `img_img_brake_lights_on`, are of size 186x172.

### PR DESCRIPTION
**Pull request by kissa96**
[Related issue](https://github.com/lvgl/lvgl/issues/6837)
Fixes #6837

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thanks you! 

A few notes: 
- Please use PR titles like `fix(obj): fix crash with LV_SIZE_CONTENT parent and % positioned child `
- In the PR description add Fixes #6837 to let GitHub close the issue when the PR is merged.
- Please add a test as described [here](https://github.com/lvgl/lvgl/blob/master/tests/README.md)

File: src/core/lv_obj_pos.c [hunk 1]
```diff
@@ -627,6 +627,18 @@ void lv_obj_refr_pos(lv_obj_t * obj)
     if(LV_COORD_IS_PCT(x)) x = (pw * LV_COORD_GET_PCT(x)) / 100;
     if(LV_COORD_IS_PCT(y)) y = (ph * LV_COORD_GET_PCT(y)) / 100;
 
+    /*Handle positionings*/
+    if(pw) {
```
Comment (ghost) [inline src/core/lv_obj_pos.c]: Why not fold the two ifs? I.e. `if (pw && LV_COORD_IS_PCT(x) && LV_COORD_GET_PCT(x))...`?

Comment (kissa96) [reply src/core/lv_obj_pos.c]: Simply due to debugging purposes. It gets optimized out during compilation anyways

Comment (ghost) [reply src/core/lv_obj_pos.c]: Hmm, it would surprise me if the compiler can remove the statement, given that `pw` not known during compile time. Or what exactly do you mean by "optimized out"?

Comment (kissa96) [reply src/core/lv_obj_pos.c]: It is going to group the ifs accordingly and is going to use the least amount of branches possible. Basically it comes down to coding style

**Comment by kisvegabor** [comment]
Please don't forget to add a test :slightly_smiling_face:

**Comment by kisvegabor** [comment]
Finished, and test is added. @mvladic please try it out.

**Comment by mvladic** [comment]
> @mvladic please try it out.

I can confirm that this fixed the issue when parent size is set to `LV_SIZE_CONTENT` and child widget is using `LV_PCT`. I can see that `LV_PCT` in this case is now ignored and value `0` is used instead.

**Review by liamHowatt — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]
