### PR TITLE
fix(refr): call flush_wait_cb only if flushing is in progress

### LINKED ISSUE #6038: Flush wait callback clarifications
### LVGL version

v9.1.0

### What happened?

I am currently working on migrating the zephyr gluecode to the new v9.1.0 release. In the past (v8.4) we had support for a seperate flush thread which would speed up rendering by quite a bit. It seems like some underlying assumption that LVGL makes in regards to flushing and waiting for the flush to finish has changed in the new release. This is the basic setup that we are using on v9.1.0:

```
struct lvgl_display_flush {
	lv_display_t *display;
	uint16_t x;
	uint16_t y;
	struct display_buffer_descriptor desc;
	void *buf;
};

K_SEM_DEFINE(flush_complete, 0, 1);
/* Message queue will only ever need to queue one message */
K_MSGQ_DEFINE(flush_queue, sizeof(struct lvgl_display_flush), 1, 1);

void lvgl_flush_thread_entry(void *arg1, void *arg2, void *arg3)
{
	struct lvgl_display_flush flush;
	struct lvgl_disp_data *data;

	while (1) {
		k_msgq_get(&flush_queue, &flush, K_FOREVER);
		data = (struct lvgl_disp_data *)lv_display_get_user_data(flush.display);

		display_write(data->display_dev, flush.x, flush.y, &flush.desc, flush.buf);

		lv_display_flush_ready(flush.display);
		k_sem_give(&flush_complete);
	}
}

K_THREAD_DEFINE(lvgl_flush_thread, CONFIG_LV_Z_FLUSH_THREAD_STACK_SIZE, lvgl_flush_thread_entry,
		NULL, NULL, NULL, K_PRIO_COOP(CONFIG_LV_Z_FLUSH_THREAD_PRIO), 0, 0);

void lvgl_wait_cb(lv_display_t *display)
{
	k_sem_take(&flush_complete, K_FOREVER);
}

void lvgl_flush_display(struct lvgl_display_flush *request)
{
	/*
	 * LVGL will only start a flush once the previous one is complete,
	 * so we can reset the flush state semaphore here.
	 */
	k_sem_reset(&flush_complete);
	k_msgq_put(&flush_queue, request, K_FOREVER);
	/* Explicitly yield, in case the calling thread is a cooperative one */
	k_yield();
}

void lvgl_flush_cb_24bit(lv_display_t *display, const lv_area_t *area, uint8_t *px_map)
{
	uint16_t w = area->x2 - area->x1 + 1;
	uint16_t h = area->y2 - area->y1 + 1;
	struct lvgl_display_flush flush;

	flush.display = display;
	flush.x = area->x1;
	flush.y = area->y1;
	flush.desc.buf_size = w * 3U * h;
	flush.desc.width = w;
	flush.desc.pitch = w;
	flush.desc.height = h;
	flush.buf = (void *)px_map;
	lvgl_flush_display(&flush);
}

void set_lvgl_rendering_cb(lv_display_t *display)
{
	lv_display_set_flush_wait_cb(display, lvgl_wait_cb);
	lv_display_set_flush_cb(display, lvgl_flush_cb_24bit);
}
```

So essentially we have `lvgl_flush_thread` which is waiting for any new flush task in the `flush_queue`. After processing the item the thread gives the `flush_complete` semaphore, which is awaited by the wait callback.

Setting a breakpoint on `lvgl_wait_cb` I can see it is called before the `lvgl_flush_display` is called even once - leading to eternal waiting on the semaphore. What is the intended behaviour for the flush callback? Does it need to perform checks if flushing is actually needed? (the queue not being empty?). Is calling `lv_display_flush_ready` still needed?

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by kisvegabor**
fixes #6038

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by FASTSHIFT — APPROVED** [review]

File: src/core/lv_refr.c [hunk 1]
```diff
@@ -1078,7 +1078,10 @@ static void wait_for_flushing(lv_display_t * disp)
     lv_display_send_event(disp, LV_EVENT_FLUSH_WAIT_START, NULL);
 
     if(disp->flush_wait_cb) {
-        disp->flush_wait_cb(disp);
+        if(disp->flushing) {
+            disp->flush_wait_cb(disp);
+        }
+        disp->flushing = 0;
```
Comment (XuNeo) [inline src/core/lv_refr.c:1084]:
```c
if(disp->flushing && disp->flush_wait_cb) {
    disp->flush_wait_cb(disp);
    disp->flushing = 0;
}
```

Comment (kisvegabor) [reply src/core/lv_refr.c:1084]: I think the original code conveys what's the intention better. By looking in to a larger snippet:
```c
    if(disp->flush_wait_cb) { //Do this if the flush_wait_cb is set
        if(disp->flushing) {
            disp->flush_wait_cb(disp);
        }
        disp->flushing = 0;
    }
    else { //This is without flush_wait_cb
        while(disp->flushing);
    }
```

Comment (XuNeo) [reply src/core/lv_refr.c:1084]: Sorry, you are right. I missed the case of `else`.

**Review by XuNeo — APPROVED** [review]
