### PR TITLE
fix(libinput): private headers

### LINKED ISSUE #6844: Bug: Compiler error in 9.2.0 when using LV_LIBINPUT_XKB=1
### LVGL version

v9.2.0

### What happened?

Compilation of my project fails with errors:

```
Compiling .pio/build/native-tft-debug/libd71/lvgl/drivers/libinput/lv_xkb.c.o
In file included from .pio/libdeps/native-tft-debug/lvgl/src/drivers/libinput/lv_xkb_private.h:17,
                 from .pio/libdeps/native-tft-debug/lvgl/src/drivers/libinput/lv_xkb.c:10:
.pio/libdeps/native-tft-debug/lvgl/src/drivers/libinput/lv_xkb.h:36:18: error: unknown type name ‘lv_xkb_t’
   36 | bool lv_xkb_init(lv_xkb_t * dsc, struct xkb_rule_names names);
      |                  ^~~~~~~~
.pio/libdeps/native-tft-debug/lvgl/src/drivers/libinput/lv_xkb.h:42:20: error: unknown type name ‘lv_xkb_t’
   42 | void lv_xkb_deinit(lv_xkb_t * dsc);
      |                    ^~~~~~~~
.pio/libdeps/native-tft-debug/lvgl/src/drivers/libinput/lv_xkb.h:51:29: error: unknown type name ‘lv_xkb_t’
   51 | uint32_t lv_xkb_process_key(lv_xkb_t * dsc, uint32_t scancode, bool down);
      |                             ^~~~~~~~
*** [.pio/build/native-tft-debug/libd71/lvgl/drivers/libinput/lv_xkb.c.o] Error 1
```

The error can be fixed by adding
`#include "../../misc/lv_types.h"`
to file _src/drivers/libinput/lv_xkb.c_

image

### How to reproduce?

Build lvgl project with LV_USE_LIBINPUT=1 and LV_LIBINPUT_XKB=1

### PR DESCRIPTION
**Pull request by liamHowatt**
Fixes #6844

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — DISMISSED** [review]

File: src/drivers/libinput/lv_libinput_private.h [hunk 1]
```diff
@@ -18,6 +18,8 @@ extern "C" {
 
 #if LV_USE_LIBINPUT
 
+#include "lv_xkb_private.h"
```
Comment (mverch67) [inline src/drivers/libinput/lv_libinput_private.h:22]: is this include correct?
Including xkb headers **independent** of value LV_LIBINPUT_XKB?

Asking because for Linux it may require installing libxkbcommon-dev even xkb is not used (i.e. not defined 1 in lv_conf.h).

Comment (liamHowatt) [reply src/drivers/libinput/lv_libinput_private.h:22]: Yes it would be ok because `lv_xkb.h` will not try to include `xkbcommon` or declare anything unless `LV_LIBINPUT_XKB` is `1`.

But for clarity and consistency, I have pushed a change :+1:

**Review by kisvegabor — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]

**Comment by mverch67** [comment]
I tried to compile on a raspberry pi and still got errors in lv_libinput_private.h:

The two struct definitions should probably be defined **without** the leading underscore:
```

struct _lv_libinput_event_t
struct _lv_libinput_t
```

as they are used only without the underscore.
