### PR TITLE
fix(file_explorer): fix navigation handling

### LINKED ISSUE #7118: File Explorer path issue
### LVGL version

9.3.0

### What happened?

When play with the File Explorer function on my stm32 board with a touchscreen, the File Explorer seems have some path issue.
When you click to enter a folder and click .. back, it works, but after that you click to enter a folder a sencond time ,it dose not work.

The examples on https://docs.lvgl.io/master/others/file_explorer.html seems have the similar path issue:
 You click to enter a folder and click .. back, then click to enter a folder a sencond time and click .., it will not work. I notice that the path is not correct.

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by C47D**
Fixes #7118 and fixes compilation of `file explorer example 2`

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kissa96 — APPROVED** [review]
lgtm

File: src/others/file_explorer/lv_file_explorer.c [hunk 1]
```diff
@@ -483,27 +486,43 @@ static void browser_file_event_handler(lv_event_t * e)
...
+        uint8_t navigate_to_current_dir = 0;
+        uint8_t navigate_to_parent_dir = 0;
+        uint8_t navigate_to_child = 0;
 
         lv_memzero(file_name, sizeof(file_name));
         lv_table_get_selected_cell(explorer->file_table, &row, &col);
-        str_fn = lv_table_get_cell_value(explorer->file_table, row, col);
+        selected_text = lv_table_get_cell_value(explorer->file_table, row, col);
+
+        selected_text = selected_text + 5; // skip table cell format
```
Comment (liamHowatt) [inline src/others/file_explorer/lv_file_explorer.c]:
```suggestion
        selected_text = selected_text + 5; /* skip table cell format */
```

**Review by liamHowatt — COMMENTED** [review]
My of my own applications is not crashing anymore after these changes. Nice!

There is another issue I've been seeing. There's a use-after-free bug detected when the address sanitizer is enabled. It's related to the table cells. Don't try to fix it in this PR. Just fyi.

<details>
    <summary>Crash info</summary>

    ```
    ==51600==ERROR: AddressSanitizer: heap-use-after-free on address 0x6040000602e0 at pc 0x7f53c69fe070 bp 0x7ffcceb52870 sp 0x7ffcceb52018
    READ of size 14 at 0x6040000602e0 thread T0
        #0 0x7f53c69fe06f in __interceptor_strcpy ../../../../src/libsanitizer/asan/asan_interceptors.cc:430
        #1 0x5609a29bf291 in lv_strcpy /home/liam/lvgl/lvgl/src/stdlib/clib/lv_string_clib.c:81
        #2 0x5609a2a3f145 in copy_cell_txt /home/liam/lvgl/lvgl/src/widgets/table/lv_table.c:1057
        #3 0x5609a2a36a0f in lv_table_set_cell_value /home/liam/lvgl/lvgl/src/widgets/table/lv_table.c:119
        #4 0x5609a2b1a976 in exch_table_item /home/liam/lvgl/lvgl/examples/others/file_explorer/lv_example_file_explorer_3.c:14
        #5 0x5609a2b1ab58 in sort_by_file_kind /home/liam/lvgl/lvgl/examples/others/file_explorer/lv_example_file_explorer_3.c:36
        #6 0x5609a2b1ac83 in file_explorer_event_handler /home/liam/lvgl/lvgl/examples/others/file_explorer/lv_example_file_explorer_3.c:60
        #7 0x5609a29b3ced in lv_event_send /home/liam/lvgl/lvgl/src/misc/lv_event.c:98
        #8 0x5609a2a5b21c in event_send_core /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:367
        #9 0x5609a2a59cf8 in lv_obj_send_event /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:67
        #10 0x5609a2b1c9c6 in show_dir /home/liam/lvgl/lvgl/src/others/file_explorer/lv_file_explorer.c:617
        #11 0x5609a2b1bedd in browser_file_event_handler /home/liam/lvgl/lvgl/src/others/file_explorer/lv_file_explorer.c:531
        #12 0x5609a29b3ced in lv_event_send /home/liam/lvgl/lvgl/src/misc/lv_event.c:98
        #13 0x5609a2a5b21c in event_send_core /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:367
        #14 0x5609a2a59cf8 in lv_obj_send_event /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:67
        #15 0x5609a2a3af00 in lv_table_event /home/liam/lvgl/lvgl/src/widgets/table/lv_table.c:595
        #16 0x5609a2a59f41 in lv_obj_event_base /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:89
        #17 0x5609a2a5b1b1 in event_send_core /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:364
        #18 0x5609a2a59cf8 in lv_obj_send_event /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:67
        #19 0x5609a29a2bb3 in send_event /home/liam/lvgl/lvgl/src/indev/lv_indev.c:1740
        #20 0x5609a29a01b9 in indev_proc_release /home/liam/lvgl/lvgl/src/indev/lv_indev.c:1359
        #21 0x5609a299b742 in indev_pointer_proc /home/liam/lvgl/lvgl/src/indev/lv_indev.c:725
        #22 0x5609a2998a44 in lv_indev_read /home/liam/lvgl/lvgl/src/indev/lv_indev.c:251
        #23 0x5609a2992748 in lv_sdl_mouse_handler /home/liam/lvgl/lvgl/src/drivers/sdl/lv_sdl_mouse.c:201
        #24 0x5609a2993a59 in sdl_event_handler /home/liam/lvgl/lvgl/src/drivers/sdl/lv_sdl_window.c:272
        #25 0x5609a29bdd8f in lv_timer_exec /home/liam/lvgl/lvgl/src/misc/lv_timer.c:325
        #26 0x5609a29bcad9 in lv_timer_handler /home/liam/lvgl/lvgl/src/misc/lv_timer.c:107
        #27 0x5609a2961d60 in main /home/liam/lvgl/lvgl_workspace/main.c:3396
        #28 0x7f53c54e9082 in __libc_start_main ../csu/libc-start.c:308
        #29 0x5609a2961c2d in _start (/home/liam/lvgl/lvgl_workspace/build/lvgl_workspace+0x33c2d)

    0x6040000602e0 is located 16 bytes inside of 38-byte region [0x6040000602d0,0x6040000602f6)
    freed by thread T0 here:
        #0 0x7f53c6a6fc3e in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:163
        #1 0x5609a29bee5e in lv_realloc_core /home/liam/lvgl/lvgl/src/stdlib/clib/lv_mem_core_clib.c:69
        #2 0x5609a29bf54d in lv_realloc /home/liam/lvgl/lvgl/src/stdlib/lv_mem.c:150
        #3 0x5609a2a3685d in lv_table_set_cell_value /home/liam/lvgl/lvgl/src/widgets/table/lv_table.c:115
        #4 0x5609a2b1a976 in exch_table_item /home/liam/lvgl/lvgl/examples/others/file_explorer/lv_example_file_explorer_3.c:14
        #5 0x5609a2b1ab58 in sort_by_file_kind /home/liam/lvgl/lvgl/examples/others/file_explorer/lv_example_file_explorer_3.c:36
        #6 0x5609a2b1ac83 in file_explorer_event_handler /home/liam/lvgl/lvgl/examples/others/file_explorer/lv_example_file_explorer_3.c:60
        #7 0x5609a29b3ced in lv_event_send /home/liam/lvgl/lvgl/src/misc/lv_event.c:98
        #8 0x5609a2a5b21c in event_send_core /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:367
        #9 0x5609a2a59cf8 in lv_obj_send_event /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:67
        #10 0x5609a2b1c9c6 in show_dir /home/liam/lvgl/lvgl/src/others/file_explorer/lv_file_explorer.c:617
        #11 0x5609a2b1bedd in browser_file_event_handler /home/liam/lvgl/lvgl/src/others/file_explorer/lv_file_explorer.c:531
        #12 0x5609a29b3ced in lv_event_send /home/liam/lvgl/lvgl/src/misc/lv_event.c:98
        #13 0x5609a2a5b21c in event_send_core /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:367
        #14 0x5609a2a59cf8 in lv_obj_send_event /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:67
        #15 0x5609a2a3af00 in lv_table_event /home/liam/lvgl/lvgl/src/widgets/table/lv_table.c:595
        #16 0x5609a2a59f41 in lv_obj_event_base /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:89
        #17 0x5609a2a5b1b1 in event_send_core /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:364
        #18 0x5609a2a59cf8 in lv_obj_send_event /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:67
        #19 0x5609a29a2bb3 in send_event /home/liam/lvgl/lvgl/src/indev/lv_indev.c:1740
        #20 0x5609a29a01b9 in indev_proc_release /home/liam/lvgl/lvgl/src/indev/lv_indev.c:1359
        #21 0x5609a299b742 in indev_pointer_proc /home/liam/lvgl/lvgl/src/indev/lv_indev.c:725
        #22 0x5609a2998a44 in lv_indev_read /home/liam/lvgl/lvgl/src/indev/lv_indev.c:251
        #23 0x5609a2992748 in lv_sdl_mouse_handler /home/liam/lvgl/lvgl/src/drivers/sdl/lv_sdl_mouse.c:201
        #24 0x5609a2993a59 in sdl_event_handler /home/liam/lvgl/lvgl/src/drivers/sdl/lv_sdl_window.c:272
        #25 0x5609a29bdd8f in lv_timer_exec /home/liam/lvgl/lvgl/src/misc/lv_timer.c:325
        #26 0x5609a29bcad9 in lv_timer_handler /home/liam/lvgl/lvgl/src/misc/lv_timer.c:107
        #27 0x5609a2961d60 in main /home/liam/lvgl/lvgl_workspace/main.c:3396
        #28 0x7f53c54e9082 in __libc_start_main ../csu/libc-start.c:308

    previously allocated by thread T0 here:
        #0 0x7f53c6a6fc3e in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:163
        #1 0x5609a29bee5e in lv_realloc_core /home/liam/lvgl/lvgl/src/stdlib/clib/lv_mem_core_clib.c:69
        #2 0x5609a29bf54d in lv_realloc /home/liam/lvgl/lvgl/src/stdlib/lv_mem.c:150
        #3 0x5609a2a37092 in lv_table_set_cell_value_fmt /home/liam/lvgl/lvgl/src/widgets/table/lv_table.c:183
        #4 0x5609a2b1c4ff in show_dir /home/liam/lvgl/lvgl/src/others/file_explorer/lv_file_explorer.c:585
        #5 0x5609a2b1bedd in browser_file_event_handler /home/liam/lvgl/lvgl/src/others/file_explorer/lv_file_explorer.c:531
        #6 0x5609a29b3ced in lv_event_send /home/liam/lvgl/lvgl/src/misc/lv_event.c:98
        #7 0x5609a2a5b21c in event_send_core /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:367
        #8 0x5609a2a59cf8 in lv_obj_send_event /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:67
        #9 0x5609a2a3af00 in lv_table_event /home/liam/lvgl/lvgl/src/widgets/table/lv_table.c:595
        #10 0x5609a2a59f41 in lv_obj_event_base /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:89
        #11 0x5609a2a5b1b1 in event_send_core /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:364
        #12 0x5609a2a59cf8 in lv_obj_send_event /home/liam/lvgl/lvgl/src/core/lv_obj_event.c:67
        #13 0x5609a29a2bb3 in send_event /home/liam/lvgl/lvgl/src/indev/lv_indev.c:1740
        #14 0x5609a29a01b9 in indev_proc_release /home/liam/lvgl/lvgl/src/indev/lv_indev.c:1359
        #15 0x5609a299b742 in indev_pointer_proc /home/liam/lvgl/lvgl/src/indev/lv_indev.c:725
        #16 0x5609a2998a44 in lv_indev_read /home/liam/lvgl/lvgl/src/indev/lv_indev.c:251
        #17 0x5609a2992748 in lv_sdl_mouse_handler /home/liam/lvgl/lvgl/src/drivers/sdl/lv_sdl_mouse.c:201
        #18 0x5609a2993a59 in sdl_event_handler /home/liam/lvgl/lvgl/src/drivers/sdl/lv_sdl_window.c:272
        #19 0x5609a29bdd8f in lv_timer_exec /home/liam/lvgl/lvgl/src/misc/lv_timer.c:325
        #20 0x5609a29bcad9 in lv_timer_handler /home/liam/lvgl/lvgl/src/misc/lv_timer.c:107
        #21 0x5609a2961d60 in main /home/liam/lvgl/lvgl_workspace/main.c:3396
        #22 0x7f53c54e9082 in __libc_start_main ../csu/libc-start.c:308
    ```
</details>

**Comment by C47D** [comment]
> My of my own applications is not crashing anymore after these changes. Nice!
> 
> There is another issue I've been seeing. There's a use-after-free bug detected when the address sanitizer is enabled. It's related to the table cells. Don't try to fix it in this PR. Just fyi.
> Crash info

Hi, thanks for the information, I'll try to take a look at it this week.

**Review by liamHowatt — DISMISSED** [review]

**Review by liamHowatt — COMMENTED** [review]
Sorry, I just noticed the `btn_event_handler` and `dd_event_handler` functions in lv_example_file_explorer_2.c should be wrapped in a `LV_FILE_EXPLORER_QUICK_ACCESS` guard too to avoid a warning.

**Comment by liamHowatt** [comment]
> Hi, thanks for the information, I'll try to take a look at it this week. It happens in example 3 demo? Also, do you have `LV_FILE_EXPLORER_QUICK_ACCESS` enabled?

I replied in the issue.

File: src/others/file_explorer/lv_file_explorer.c [hunk 2]
```diff
@@ -512,8 +531,8 @@ static void browser_file_event_handler(lv_event_t * e)
             show_dir(obj, (char *)file_name);
```
Comment (Orange-Murker) [inline src/others/file_explorer/lv_file_explorer.c:531]: My concern here is that if the directory fails to open for some reason we will end up with a broken path. It is a good idea to revert the path to its previous state instead of assuming that the selected item is not a directory if it failed to open as a directory.

File: src/others/file_explorer/lv_file_explorer.c [hunk 3]
```diff
@@ -512,8 +531,8 @@ static void browser_file_event_handler(lv_event_t * e)
...
         }
         else {
```
Comment (Orange-Murker) [inline src/others/file_explorer/lv_file_explorer.c:533]: Here we can use the second column of the table to determine whether or not the selected item is a directory.

**Review by Orange-Murker — CHANGES_REQUESTED** [review]

**Comment by C47D** [comment]
Hi @GorgonMeducer , I agree with both suggestions, but do you think we can update it in other PR?

**Comment by C47D** [comment]
> I could make another PR for those changes. Then this one needs to be merged first.

Sorry, i confused your user, so I think this is ready to be merged then :smile:

**Review by Orange-Murker — APPROVED** [review]

**Review by liamHowatt — APPROVED** [review]
> Fixed in [dacbd7b](https://github.com/lvgl/lvgl/commit/dacbd7bb44267117dacd7285bc1601be0c7eff1e)

Thanks!

**Review by kissa96 — APPROVED** [review]

File: src/others/file_explorer/lv_file_explorer.c (hunk 2 above)
Comment (kisvegabor) [reply src/others/file_explorer/lv_file_explorer.c:531]: @C47D is it already addressed?

Comment (C47D) [reply src/others/file_explorer/lv_file_explorer.c:531]: It will be addressed in a separated PR, see https://github.com/lvgl/lvgl/pull/7124#issuecomment-2430415434

**Review by FASTSHIFT — APPROVED** [review]
