### PR TITLE
fix(sysmon): support starting LVGL without having a display

### LINKED ISSUE #4926: Finalize v9
Continue #3298 (see for the changes too)

### Schedule
1. **December 4**: Feature stop, start updating the docs and testing
2. **December 18**: Release candidate version and call to test
3. **January 15**: Release v9.0

### 1. Features to finalize
We don't add any new features but finalize these ongoing ones 
- [ ] Image decoder fine tuning (@XuNeo )
- [ ] Online image converter (@W-Mai)
- [ ] Cache update (@W-Mai and @FASTSHIFT #4835 )
- [x] Scale needle handling (@lhdjply ? #4917)
- [ ] Pointer scroll support (@kisvegabor / @XuNeo #4909)
- [ ] Add ESP-LCD support (@zjanosy  #4507)
- [ ] Add support for at least 3 display controller (@zjanosy)
- [x] Remove the MicroPython examples and replace them with a test (@kdschlosser #4645)

### 2. Prepare for release candidate (by December 18)
Docs review
- [x] [Porting](https://docs.lvgl.io/master/porting/index.html) (@kisvegabor )
- [x] [Drivers](https://docs.lvgl.io/master/integration/index.html) ( :warning: Help wanted)
- [x] [Widgets](https://docs.lvgl.io/master/widgets/index.html) (@kisvegabor )
- [x] [Overview](https://docs.lvgl.io/master/overview/index.html) (especially the image part)  ( :warning: Help wanted)

Demos end examples
- [x] [Examples](https://docs.lvgl.io/master/examples.html) (@kisvegabor )
- [ ] Review and update demos (@kisvegabor )

Others
- [x] Migration guide (@kisvegabor)
- [x] **Call to test and announce release candidate**  (@kisvegabor )
 
### 3. Fixes and last touches (by January 15)
Mainly for January
- [ ] CI update with more config options (@XuNeo and @kisvegabor)
- [ ] Final NXP drivers (@nicusorcitu)
- [ ] Arm2D support? (@GorgonMeducer )
- [ ] Project update (E.g. Eclipse, VSCode, etc)  ( :warning:  Help wanted)
- [x] Changelog (@kisvegabor)
- [ ] **Release** (@kisvegabor )

### PR DESCRIPTION
**Pull request by kisvegabor**
### Description of the feature or fix

fixes https://github.com/lvgl/lvgl/issues/4926#issuecomment-1911631548

cc @espzav

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by W-Mai — APPROVED** [review]

File: src/others/sysmon/lv_sysmon.c [hunk 1]
```diff
@@ -144,10 +143,25 @@ static void perf_monitor_disp_event_cb(lv_event_t * e)
             break;
     }
 }
-uint32_t lv_os_get_idle_percent(void);
 
 static void perf_update_timer_cb(lv_timer_t * t)
 {
+    static bool inited = false;
```
Comment (FASTSHIFT) [inline src/others/sysmon/lv_sysmon.c]: Multiple instances of lvgl will cause problems, consider moving to `lv_global_t`.

Comment (kisvegabor) [reply src/others/sysmon/lv_sysmon.c]: True, fixed.

**Review by FASTSHIFT — APPROVED** [review]
